# Generated by Django 5.2.1 on 2025-07-30 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IR_yearly', models.IntegerField(default=0)),
                ('IR_monthly', models.IntegerField(default=0)),
                ('TR_yearly', models.IntegerField(default=0)),
                ('TR_monthly', models.IntegerField(default=0)),
                ('EN_yearly', models.IntegerField(default=0)),
                ('EN_monthly', models.IntegerField(default=0)),
                ('token1M', models.IntegerField(default=0)),
                ('token3M', models.IntegerField(default=0)),
                ('token5M', models.IntegerField(default=0)),
                ('token10M', models.IntegerField(default=0)),
                ('email1K', models.IntegerField(default=0)),
                ('email3K', models.IntegerField(default=0)),
                ('email5K', models.IntegerField(default=0)),
                ('email10K', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '💰 System Settings',
                'verbose_name_plural': '💰 System Settings',
            },
        ),
        migrations.CreateModel(
            name='AIPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_prompt', models.TextField(blank=True, max_length=2000, null=True)),
                ('knowledge_source', models.JSONField(blank=True, null=True)),
                ('product_service', models.JSONField(blank=True, null=True)),
                ('question_answer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🤖 AI Prompt',
                'verbose_name_plural': '🤖 AI Prompts',
            },
        ),
        migrations.CreateModel(
            name='InstagramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connect', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('instagram_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('followers_count', models.IntegerField(blank=True, null=True)),
                ('following_count', models.IntegerField(blank=True, null=True)),
                ('media_count', models.IntegerField(blank=True, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📷 Instagram Channel',
                'verbose_name_plural': '📷 Instagram Channels',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('support_response', 'Support Response'), ('customer_reply', 'Customer Reply'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🎫 Support Ticket',
                'verbose_name_plural': '🎫 Support Tickets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_from_support', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='settings.supportticket')),
            ],
            options={
                'verbose_name': '💬 Support Message',
                'verbose_name_plural': '💬 Support Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connect', models.BooleanField(default=False)),
                ('bot_token', models.CharField(max_length=200, unique=True)),
                ('bot_username', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📱 Telegram Channel',
                'verbose_name_plural': '📱 Telegram Channels',
            },
        ),
    ]
