# Generated by Django 5.2.1 on 2025-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
