# Generated by Django 5.2.1 on 2025-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_telegramchannel_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='department',
            field=models.CharField(choices=[('technical_support', 'Technical Support'), ('billing_support', 'Billing Support'), ('general_inquiry', 'General Inquiry'), ('account_support', 'Account Support')], default='general_inquiry', max_length=20),
        ),
    ]
