# Generated by Django 5.1.5 on 2025-08-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_supportticket_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='attachment',
        ),
        migrations.CreateModel(
            name='SupportMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='settings.supportmessage')),
            ],
            options={
                'verbose_name': '📎 Support Message Attachment',
                'verbose_name_plural': '📎 Support Message Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
