# Generated by Django 5.1.5 on 2025-08-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_supportmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '💬 Support Message', 'verbose_name_plural': '💬 Support Messages'},
        ),
    ]
