# Generated by Django 5.1.5 on 2025-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_aiprompts_auto_prompt_alter_aiprompts_manual_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Gemini API key for AI services', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '⚙️ General Settings',
                'verbose_name_plural': '⚙️ General Settings',
            },
        ),
    ]
