# Generated by Django 5.1.5 on 2025-08-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprompts',
            name='auto_prompt',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='auto_prompt',
            field=models.TextField(default='You are an AI customer service representative.\nRespond to customer inquiries professionally and helpfully.\nAlways respond in the same language the customer uses.\nKeep your responses clear and concise.', help_text='Default auto prompt for AI responses - applies to all users', max_length=5000),
        ),
    ]
