# Generated by Django 5.1.5 on 2025-08-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_aiprompts_auto_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchannel',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_bot_pictures/'),
        ),
    ]
