# Generated by Django 5.1.5 on 2025-08-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_remove_telegramchannel_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompts',
            name='manual_prompt',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
