# Generated by Django 5.1.5 on 2025-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_aiprompts_manual_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompts',
            name='manual_prompt',
            field=models.TextField(blank=True, max_length=90000000, null=True),
        ),
    ]
