# Generated by Django 5.1.5 on 2025-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_aiprompts_manual_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the business prompt', max_length=200)),
                ('prompt', models.TextField(help_text='The business prompt content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '💼 Business Prompt',
                'verbose_name_plural': '💼 Business Prompts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
