# Generated by Django 5.1.5 on 2025-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_businessprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprompt',
            name='ai_answer_prompt',
            field=models.TextField(blank=True, help_text='AI answer prompt for responses', null=True),
        ),
    ]
