# Generated by Django 5.1.5 on 2025-10-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_businessprompt_ai_answer_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpToPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(help_text='Rating value')),
                ('signedup', models.IntegerField(help_text='Number of signups')),
                ('comment', models.TextField(help_text='User comment')),
                ('name', models.CharField(help_text='User name', max_length=200)),
                ('profileimage', models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='uptopro_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '⭐ UpToPro',
                'verbose_name_plural': '⭐ UpToPros',
                'ordering': ['-created_at'],
            },
        ),
    ]
