# Generated by Django 5.1.5 on 2025-11-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_supportticket_intercom_conversation_id'),
        ('settings', '0014_uptopro_generalsettings_openai_api_key'),
    ]

    operations = [
    ]
