# Safe migration that handles existing tables and fields
# Generated by Django 5.1.5 on 2025-11-25 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def safe_create_intercom_ticket_type(apps, schema_editor):
    """
    Safely create IntercomTicketType table if it doesn't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'settings_intercomtickettype'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            cursor.execute("""
                CREATE TABLE settings_intercomtickettype (
                    id BIGSERIAL PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    department VARCHAR(20) UNIQUE NOT NULL,
                    intercom_ticket_type_id VARCHAR(50) NOT NULL,
                    is_active BOOLEAN DEFAULT TRUE,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
            """)
            print("✅ Created IntercomTicketType table")
        else:
            print("⏭️  IntercomTicketType table already exists, skipping")


def safe_create_ai_behavior_settings(apps, schema_editor):
    """
    Safely create AIBehaviorSettings table if it doesn't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'settings_ai_behavior'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            cursor.execute("""
                CREATE TABLE settings_ai_behavior (
                    id BIGSERIAL PRIMARY KEY,
                    tone VARCHAR(20) DEFAULT 'friendly',
                    emoji_usage VARCHAR(20) DEFAULT 'moderate',
                    response_length VARCHAR(20) DEFAULT 'balanced',
                    use_customer_name BOOLEAN DEFAULT TRUE,
                    use_bio_context BOOLEAN DEFAULT TRUE,
                    persuasive_selling_enabled BOOLEAN DEFAULT FALSE,
                    persuasive_cta_text VARCHAR(300) DEFAULT 'آیا می‌خواهید این محصول را سفارش دهید؟ 🛒',
                    unknown_fallback_text VARCHAR(500) DEFAULT 'من در حال حاضر پاسخ دقیق این سوال را ندارم، اما همکارانم به زودی پاسخ شما را خواهند داد.',
                    custom_instructions TEXT,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    user_id BIGINT UNIQUE NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                )
            """)
            print("✅ Created AIBehaviorSettings table")
        else:
            print("⏭️  AIBehaviorSettings table already exists, skipping")


def safe_add_fields_to_generalsettings(apps, schema_editor):
    """
    Safely add fields to GeneralSettings if they don't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Get existing columns
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='settings_generalsettings' AND table_schema='public'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        fields_to_add = [
            ("ai_role", "TEXT DEFAULT 'You are a sales assistant, NOT a support agent.\nYour goal is to understand customer needs and recommend relevant products/services.\nAlways look for opportunities to suggest products that match their needs.\nBe helpful, friendly, and proactive in offering solutions.'"),
            ("anti_hallucination_rules", "TEXT DEFAULT '🚨 قوانین ضد توهم‌زایی (Critical):\n\n1) همیشه اول کانتکست و نالج را چک کن:\n   - اگر chunk/FAQ/محصول/سایت در کانتکست هست → از همان استفاده کن\n   - اگر چیزی در کانتکست نیست، خودت اطلاعات نساز\n\n2) این‌ها را هرگز اختراع نکن:\n   - آدرس، شماره تماس، قیمت، موجودی، لینک\n   - جزئیات محصول یا خدماتی که تو کانتکست نیست\n   - هیچ‌وقت نگو \"الان می‌فرستم\" اگر الان نداری\n\n3) اگر اطلاعات نداری:\n   - صادقانه بگو: \"این اطلاعات الان تو دانش من نیست\"\n   - از متن knowledge_limitation_response استفاده کن\n\n4) لینک و وب‌سایت (خیلی مهم):\n   - اگر فقط یک لینک می‌بینی و محتوای صفحه در کانتکست نیست، اصلاً حدس نزن\n   - بگو: \"متأسفانه من نمی‌تونم محتوای این لینک را ببینم. اگر سوالی راجع بهش داری، لطفاً توضیح بده.\"\n   \n   ⚠️ CRITICAL: If user sends ONLY a URL without context:\n   - NEVER guess what the link is about\n   - Say you can''t see the content\n\n5) پست/ریلز اینستاگرام:\n   - تو فقط caption/متن را می‌بینی، نه تصویر/ویدیو\n   - بر اساس همان متن جواب بده، نه چیزی که داخل تصویر ممکن است باشد'"),
            ("custom_instructions", "TEXT"),
            ("greeting_rules", "TEXT DEFAULT '⛔ CRITICAL RULE: Say ''سلام'' or ''Hi'' ONLY ONCE per conversation!\n\nWhen you see \"SCENARIO: FIRST_MESSAGE\":\n→ Greet with customer''s name ONCE: \"سلام [نام]!\"\n→ Then answer their question naturally\n\nWhen you see \"SCENARIO: WELCOME_BACK\":\n→ Say \"خوش برگشتی!\" ONCE (do NOT say سلام)\n→ Then answer directly\n\nWhen you see \"SCENARIO: RECENT_CONVERSATION\":\n→ Do NOT greet at all\n→ Answer the question DIRECTLY without any greeting word\n→ Example: \"بله، می‌تونم کمک کنم...\"\n\n⛔ NEVER say \"دوباره سلام\" or repeat any greeting!'"),
            ("knowledge_limitation_response", "TEXT DEFAULT 'متأسفانه این اطلاعات رو ندارم. می‌تونم بهت درباره محصولات اصلی‌مون کمک کنم، یا می‌خوای با تیم پشتیبانی صحبت کنی؟'"),
            ("language_rules", "TEXT DEFAULT 'Always reply in Persian (Farsi).\nConvert Latin names to Persian equivalents (e.g., Omid → امید).\nUse everyday Persian expressions, not formal sentences.'"),
            ("link_handling_rules", "TEXT DEFAULT '🔗 LINK RULES:\n1. For IMPORTANT links (website/product): [[CTA:عنوان|https://url]]\n   Example: [[CTA:سایت ما|https://pilito.com]]\n2. For casual links: plain URL (https://...)\n3. NEVER use placeholders like [link] or invent URLs'"),
            ("openai_api_key", "VARCHAR(200)"),
            ("response_guidelines", "TEXT DEFAULT 'Maximum 600 characters for Instagram compatibility.\nMaximum 3-4 sentences per response.\nLimit emojis to 1 per message.\nAvoid long introductions — go straight to the point.\nIf topic is complex, give a short summary. User can ask for details.\n\n🎯 PERSONALIZATION WITH BIO:\n- If customer has a bio, USE IT in your first response\n- Mention their work/interest naturally to show you understand them\n- Example: \"دیدم استراتژیست برندینگ هستی، فیکو برات عالیه!\"\n- Convert Latin names to Persian (Omid → امید)\n\n📷🎤 MEDIA MESSAGE RULE:\n- If you see ''[sent an image]:'', the customer SENT an image (not described it)\n- If you see ''[sent a voice message]:'', the customer SENT audio (not typed it)\n- The text after is AI analysis of their media\n- Respond naturally about what they sent, don''t say ''you described'''"),
            ("response_length", "VARCHAR(20) DEFAULT 'concise'"),
            ("tone_and_style", "TEXT DEFAULT 'Speak casually and emotionally, not like a brochure.\nWrite like a person chatting on Instagram.\nKeep responses under 2 short lines.'"),
            ("welcome_back_threshold_hours", "INTEGER DEFAULT 12"),
        ]
        
        for field_name, field_def in fields_to_add:
            if field_name not in existing_columns:
                try:
                    cursor.execute(f"""
                        ALTER TABLE settings_generalsettings 
                        ADD COLUMN {field_name} {field_def}
                    """)
                    print(f"✅ Added {field_name} column")
                except Exception as e:
                    print(f"⚠️  Could not add {field_name}: {e}")
            else:
                print(f"⏭️  {field_name} column already exists, skipping")


def safe_add_fields_to_supportticket(apps, schema_editor):
    """
    Safely add fields to SupportTicket if they don't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Get existing columns
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='settings_supportticket' AND table_schema='public'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        if 'intercom_ticket_id' not in existing_columns:
            try:
                cursor.execute("""
                    ALTER TABLE settings_supportticket 
                    ADD COLUMN intercom_ticket_id VARCHAR(255) UNIQUE
                """)
                print("✅ Added intercom_ticket_id column")
            except Exception as e:
                print(f"⚠️  Could not add intercom_ticket_id: {e}")
        else:
            print("⏭️  intercom_ticket_id column already exists, skipping")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - be careful with this in production!
    """
    pass  # We won't remove tables/columns in reverse to avoid data loss


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_merge_20251125_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create IntercomTicketType table safely
        migrations.RunPython(safe_create_intercom_ticket_type, reverse_migration),
        
        # Create AIBehaviorSettings table safely
        migrations.RunPython(safe_create_ai_behavior_settings, reverse_migration),
        
        # Add fields to GeneralSettings safely
        migrations.RunPython(safe_add_fields_to_generalsettings, reverse_migration),
        
        # Add fields to SupportTicket safely
        migrations.RunPython(safe_add_fields_to_supportticket, reverse_migration),
    ]
