# Generated by Django 5.1.5 on 2025-11-25 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_merge_20251125_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercomTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ticket type name (e.g., 'Technical Support', 'Billing Issue')", max_length=100)),
                ('department', models.CharField(choices=[('technical_support', 'Technical Support'), ('billing_support', 'Billing Support'), ('general_inquiry', 'General Inquiry'), ('account_support', 'Account Support')], help_text='Department to map this ticket type to', max_length=20, unique=True)),
                ('intercom_ticket_type_id', models.CharField(help_text="Intercom Ticket Type ID from Intercom settings (e.g., '2918773')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ticket type is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🎫 Intercom Ticket Type',
                'verbose_name_plural': '🎫 Intercom Ticket Types',
                'ordering': ['department'],
            },
        ),
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': '⚙️ General AI Settings', 'verbose_name_plural': '⚙️ General AI Settings'},
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='ai_role',
            field=models.TextField(default='You are a sales assistant, NOT a support agent.\nYour goal is to understand customer needs and recommend relevant products/services.\nAlways look for opportunities to suggest products that match their needs.\nBe helpful, friendly, and proactive in offering solutions.', help_text="تعریف کنید هوش مصنوعی چه کسی است (مثلاً 'یک دستیار فروش دوستانه' یا 'یک مشاور فنی')\nاین بخش هویت اصلی AI را مشخص می\u200cکند.", max_length=500, verbose_name='🤖 AI Role & Identity'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='anti_hallucination_rules',
            field=models.TextField(default='🚨 قوانین ضد توهم\u200cزایی (Critical):\n\n1) همیشه اول کانتکست و نالج را چک کن:\n   - اگر chunk/FAQ/محصول/سایت در کانتکست هست → از همان استفاده کن\n   - اگر چیزی در کانتکست نیست، خودت اطلاعات نساز\n\n2) این\u200cها را هرگز اختراع نکن:\n   - آدرس، شماره تماس، قیمت، موجودی، لینک\n   - جزئیات محصول یا خدماتی که تو کانتکست نیست\n   - هیچ\u200cوقت نگو "الان می\u200cفرستم" اگر الان نداری\n\n3) اگر اطلاعات نداری:\n   - صادقانه بگو: "این اطلاعات الان تو دانش من نیست"\n   - از متن knowledge_limitation_response استفاده کن\n\n4) لینک و وب\u200cسایت (خیلی مهم):\n   - اگر فقط یک لینک می\u200cبینی و محتوای صفحه در کانتکست نیست، اصلاً حدس نزن\n   - بگو: "متأسفانه من نمی\u200cتونم محتوای این لینک را ببینم. اگر سوالی راجع بهش داری، لطفاً توضیح بده."\n   \n   ⚠️ CRITICAL: If user sends ONLY a URL without context:\n   - NEVER guess what the link is about\n   - Say you can\'t see the content\n\n5) پست/ریلز اینستاگرام:\n   - تو فقط caption/متن را می\u200cبینی، نه تصویر/ویدیو\n   - بر اساس همان متن جواب بده، نه چیزی که داخل تصویر ممکن است باشد', help_text='⚠️ بسیار مهم: قوانین برای جلوگیری از اطلاعات نادرست.\nمثال: \'هرگز نگو "الان می\u200cفرستم" اگر اطلاعات نداری\'\nاین قسمت از دروغ گفتن AI جلوگیری می\u200cکند.', max_length=1000, verbose_name='🚨 Anti-Hallucination Rules (قوانین ضد توهم\u200cزایی)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='دستورات اضافی که در بخش\u200cهای بالا نگنجیده است.\nاین بخش برای نیازهای خاص و منحصر به فرد شماست.\nاگر نیازی ندارید خالی بگذارید.', max_length=2000, null=True, verbose_name='⚡ Custom Instructions (دستورات سفارشی - اختیاری)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='greeting_rules',
            field=models.TextField(default='⛔ CRITICAL RULE: Say \'سلام\' or \'Hi\' ONLY ONCE per conversation!\n\nWhen you see "SCENARIO: FIRST_MESSAGE":\n→ Greet with customer\'s name ONCE: "سلام [نام]!"\n→ Then answer their question naturally\n\nWhen you see "SCENARIO: WELCOME_BACK":\n→ Say "خوش برگشتی!" ONCE (do NOT say سلام)\n→ Then answer directly\n\nWhen you see "SCENARIO: RECENT_CONVERSATION":\n→ Do NOT greet at all\n→ Answer the question DIRECTLY without any greeting word\n→ Example: "بله، می\u200cتونم کمک کنم..."\n\n⛔ NEVER say "دوباره سلام" or repeat any greeting!', help_text='قوانین برای احوالپرسی و استفاده از نام مشتری.\nشامل: first message greeting, welcome back (12+ hours), no repeat greeting\nجلوگیری از تکرار بیش از حد نام و احوالپرسی\u200cهای مزاحم.', max_length=1000, verbose_name='👋 Greeting & Name Usage (احوالپرسی و استفاده از نام)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='knowledge_limitation_response',
            field=models.TextField(default='متأسفانه این اطلاعات رو ندارم. می\u200cتونم بهت درباره محصولات اصلی\u200cمون کمک کنم، یا می\u200cخوای با تیم پشتیبانی صحبت کنی؟', help_text="پاسخ پیش\u200cفرض وقتی AI اطلاعات ندارد.\nمی\u200cتوانید از placeholder {contact_method} استفاده کنید.\nمثال: 'این اطلاعات رو ندارم، ولی از {contact_method} بپرس'", max_length=500, verbose_name='📢 Knowledge Limitation Response (پاسخ محدودیت دانش)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='language_rules',
            field=models.TextField(default='Always reply in Persian (Farsi).\nConvert Latin names to Persian equivalents (e.g., Omid → امید).\nUse everyday Persian expressions, not formal sentences.', help_text="قوانین زبانی و محلی\u200cسازی را تعریف کنید.\nمثال: 'همیشه به فارسی پاسخ بده'، 'نام\u200cهای لاتین را به فارسی تبدیل کن'\nاین قسمت تعیین می\u200cکند AI چه زبانی و با چه سبکی صحبت کند.", max_length=1000, verbose_name='🌐 Language & Localization'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='link_handling_rules',
            field=models.TextField(default='🔗 LINK RULES:\n1. For IMPORTANT links (website/product): [[CTA:عنوان|https://url]]\n   Example: [[CTA:سایت ما|https://pilito.com]]\n2. For casual links: plain URL (https://...)\n3. NEVER use placeholders like [link] or invent URLs', help_text='⚠️ بسیار مهم: قوانین برای ارسال لینک و URL.\nشامل: فرمت CTA برای دکمه\u200cهای اینستاگرام [[CTA:عنوان|URL]]\nجلوگیری از لینک\u200cهای ناقص یا جعلی.', max_length=500, verbose_name='🔗 Link & URL Handling (مدیریت لینک\u200cها)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='کلید API اوپن\u200cای\u200cآی برای embedding چندزبانه (text-embedding-3-large)', max_length=200, null=True, verbose_name='🔑 OpenAI API Key'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='response_guidelines',
            field=models.TextField(default='Maximum 600 characters for Instagram compatibility.\nMaximum 3-4 sentences per response.\nLimit emojis to 1 per message.\nAvoid long introductions — go straight to the point.\nIf topic is complex, give a short summary. User can ask for details.\n\n🎯 PERSONALIZATION WITH BIO:\n- If customer has a bio, USE IT in your first response\n- Mention their work/interest naturally to show you understand them\n- Example: "دیدم استراتژیست برندینگ هستی، فیکو برات عالیه!"\n- Convert Latin names to Persian (Omid → امید)\n\n📷🎤 MEDIA MESSAGE RULE:\n- If you see \'[sent an image]:\', the customer SENT an image (not described it)\n- If you see \'[sent a voice message]:\', the customer SENT audio (not typed it)\n- The text after is AI analysis of their media\n- Respond naturally about what they sent, don\'t say \'you described\'', help_text='قوانین اضافی برای فرمت و ساختار پاسخ\u200cها.\nشامل: طول پاسخ (600 کاراکتر برای اینستاگرام)، emoji limit، media rules\nاین بخش جزئیات فرمت پاسخ را کنترل می\u200cکند.', max_length=1000, verbose_name='📝 Response Guidelines (راهنمای پاسخ\u200cدهی)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='response_length',
            field=models.CharField(choices=[('concise', '🔹 Concise (1-2 جمله کوتاه)'), ('moderate', '🔸 Moderate (2-4 جمله متوسط)'), ('detailed', '🔶 Detailed (4+ جمله تفصیلی)')], default='concise', help_text='تعیین کنید پاسخ\u200cهای AI چقدر طولانی باشند.\nکوتاه: برای پیام\u200cهای سریع (مثل اینستاگرام)\nمتوسط: برای توضیحات کلی\nتفصیلی: برای پاسخ\u200cهای کامل و جامع', max_length=20, verbose_name='📏 Response Length (طول پاسخ)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='tone_and_style',
            field=models.TextField(default='Speak casually and emotionally, not like a brochure.\nWrite like a person chatting on Instagram.\nKeep responses under 2 short lines.', help_text="لحن و سبک مکالمه AI را تعیین کنید.\nمثال: 'صمیمی و احساسی صحبت کن'، 'مثل یک فرد واقعی در اینستاگرام بنویس'\nاین بخش شخصیت AI را شکل می\u200cدهد.", max_length=1000, verbose_name='💬 Tone & Style (لحن و سبک)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='welcome_back_threshold_hours',
            field=models.IntegerField(default=12, help_text="بعد از چند ساعت، AI باید بگوید 'خوش برگشتی'؟\nپیش\u200cفرض: 12 ساعت\nاگر مشتری بعد از این مدت برگردد، AI می\u200cگوید 'خوش برگشتی!' به جای 'سلام'", verbose_name='⏰ Welcome Back Threshold (ساعت)'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='intercom_ticket_id',
            field=models.CharField(blank=True, help_text='Intercom Ticket ID from Tickets API for two-way sync', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='auto_prompt',
            field=models.TextField(blank=True, default='You are an AI customer service representative.\nRespond to customer inquiries professionally and helpfully.\nAlways respond in the same language the customer uses.\nKeep your responses clear and concise.\n\n🔗 CRITICAL - Links & URLs:\n- Always include FULL URLs (e.g., https://fiko.net/pricing)\n- NEVER use placeholders like [link] or [URL]\n- Write complete clickable links in your responses', help_text='⚠️ این فیلد منسوخ شده است (Deprecated).\nاز فیلدهای جدید بالا استفاده کنید.\nاین فیلد فقط برای سازگاری با نسخه\u200cهای قدیم نگه داشته شده.', max_length=5000, null=True, verbose_name='⚠️ [DEPRECATED] Old Auto Prompt'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='کلید API گوگل جمینای برای سرویس\u200cهای هوش مصنوعی', max_length=200, null=True, verbose_name='🔑 Gemini API Key'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='intercom_conversation_id',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Old Conversations API ID - kept for backward compatibility', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AIBehaviorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone', models.CharField(choices=[('formal', '🎩 رسمی و حرفه\u200cای'), ('friendly', '😊 دوستانه و صمیمی'), ('energetic', '⚡ پرانرژی و هیجان\u200cانگیز'), ('empathetic', '🤝 همدلانه و حمایتگر')], default='friendly', help_text='تعیین کنید AI با چه لحنی با مشتری\u200cها صحبت کند', max_length=20, verbose_name='لحن صحبت')),
                ('emoji_usage', models.CharField(choices=[('none', '⛔ هیچ - بدون ایموجی'), ('moderate', '🙂 متعادل - کمی ایموجی'), ('high', '😍 زیاد - پر از ایموجی')], default='moderate', help_text='میزان استفاده از ایموجی در پاسخ\u200cها', max_length=20, verbose_name='استفاده از ایموجی')),
                ('response_length', models.CharField(choices=[('short', '🔹 کوتاه - 1-2 جمله'), ('balanced', '🔸 متعادل - 3-4 جمله'), ('detailed', '🔶 تفصیلی - 5-7 جمله')], default='balanced', help_text='تعیین کنید پاسخ\u200cها چقدر طولانی باشند', max_length=20, verbose_name='طول پاسخ')),
                ('use_customer_name', models.BooleanField(default=True, help_text='اگر فعال باشد، AI نام مشتری را در سلام صدا می\u200cزند', verbose_name='استفاده از نام مشتری')),
                ('use_bio_context', models.BooleanField(default=True, help_text='اگر فعال باشد، AI از بیو مشتری برای شخصی\u200cسازی استفاده می\u200cکند', verbose_name='استفاده از اطلاعات بیو')),
                ('persuasive_selling_enabled', models.BooleanField(default=False, help_text='اگر فعال باشد، AI به صورت فعال محصولات را پیشنهاد می\u200cدهد', verbose_name='فروش فعال')),
                ('persuasive_cta_text', models.CharField(blank=True, default='آیا می\u200cخواهید این محصول را سفارش دهید؟ 🛒', help_text='متنی که AI به صورت طبیعی در پیام\u200cهای فروش می\u200cگنجاند (حداکثر 300 کاراکتر)', max_length=300, verbose_name='متن دعوت به اقدام (CTA)')),
                ('unknown_fallback_text', models.CharField(default='من در حال حاضر پاسخ دقیق این سوال را ندارم، اما همکارانم به زودی پاسخ شما را خواهند داد.', help_text='دقیقاً این متن را برگردان وقتی جواب سوال را نمی\u200cدانی (حداکثر 500 کاراکتر)', max_length=500, verbose_name='پاسخ عدم اطلاع')),
                ('custom_instructions', models.TextField(blank=True, help_text='قوانین اضافی برای AI به زبان انگلیسی (اختیاری، حداکثر 1000 کاراکتر)', max_length=1000, null=True, verbose_name='دستورات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_behavior', to=settings.AUTH_USER_MODEL, verbose_name='کاربر / صاحب کسب\u200cوکار')),
            ],
            options={
                'verbose_name': '🎭 AI Behavior Settings',
                'verbose_name_plural': '🎭 AI Behavior Settings',
                'db_table': 'settings_ai_behavior',
            },
        ),
    ]
