# Generated by Django 5.1.5 on 2025-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_merge_20251016_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercomTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ticket type name (e.g., 'Technical Support', 'Billing Issue')", max_length=100)),
                ('department', models.CharField(choices=[('technical_support', 'Technical Support'), ('billing_support', 'Billing Support'), ('general_inquiry', 'General Inquiry'), ('account_support', 'Account Support')], help_text='Department to map this ticket type to', max_length=20, unique=True)),
                ('intercom_ticket_type_id', models.CharField(help_text="Intercom Ticket Type ID from Intercom settings (e.g., '2918773')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ticket type is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🎫 Intercom Ticket Type',
                'verbose_name_plural': '🎫 Intercom Ticket Types',
                'ordering': ['department'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='intercom_ticket_id',
            field=models.CharField(blank=True, help_text='Intercom Ticket ID from Tickets API for two-way sync', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='intercom_conversation_id',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Old Conversations API ID - kept for backward compatibility', max_length=255, null=True, unique=True),
        ),
    ]
