# Generated by Django 5.1.5 on 2025-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_add_modular_prompt_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='ai_role',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='anti_hallucination_rules',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='custom_instructions',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='greeting_rules',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='knowledge_limitation_response',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='language_rules',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='link_handling_rules',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='response_guidelines',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='response_length',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='tone_and_style',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='welcome_back_threshold_hours',
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='auto_prompt',
            field=models.TextField(default='You are an AI customer service representative.\nRespond to customer inquiries professionally and helpfully.\nAlways respond in the same language the customer uses.\nKeep your responses clear and concise.', help_text='Default auto prompt for AI responses - applies to all users', max_length=5000),
        ),
    ]
