# Generated by Django 5.1.5 on 2025-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_add_modular_prompt_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': '⚙️ General AI Settings', 'verbose_name_plural': '⚙️ General AI Settings'},
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='ai_role',
            field=models.TextField(default='You are a sales assistant, NOT a support agent.\nYour goal is to understand customer needs and recommend relevant products/services.\nAlways look for opportunities to suggest products that match their needs.\nBe helpful, friendly, and proactive in offering solutions.', help_text="تعریف کنید هوش مصنوعی چه کسی است (مثلاً 'یک دستیار فروش دوستانه' یا 'یک مشاور فنی')\nاین بخش هویت اصلی AI را مشخص می\u200cکند.", max_length=500, verbose_name='🤖 AI Role & Identity'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='anti_hallucination_rules',
            field=models.TextField(default='⚠️ NEVER make up information!\nIf you don\'t know something, ALWAYS say:\n- "متأسفانه اطلاعی در این مورد ندارم"\n- "نمیدونم، ولی می\u200cتونم به تیم پشتیبانی وصلت کنم"\n- "این سوال رو دقیق نمیدونم"\n\n🚫 NEVER say these when you can\'t deliver:\n- "الان می\u200cفرستم" / "باشه الان براتون ارسال می\u200cکنم"\n- "یک لحظه، الان چک می\u200cکنم"\n- "حتماً انجام میدم" / "قطعاً داریم"\n\n✅ HONEST ALTERNATIVES:\n- "می\u200cتونم لینک محصول رو بهتون بدم"\n- "اطلاعاتش رو دارم، می\u200cخوای برات بفرستم؟"\n- "در دانش من نیست، ولی تیم پشتیبانی کمکت می\u200cکنه"\n\nBe a sales assistant who admits limitations honestly.', help_text='⚠️ بسیار مهم: قوانین برای جلوگیری از اطلاعات نادرست.\nمثال: \'هرگز نگو "الان می\u200cفرستم" اگر اطلاعات نداری\'\nاین قسمت از دروغ گفتن AI جلوگیری می\u200cکند.', max_length=1000, verbose_name='🚨 Anti-Hallucination Rules (قوانین ضد توهم\u200cزایی)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='auto_prompt',
            field=models.TextField(blank=True, default='You are an AI customer service representative.\nRespond to customer inquiries professionally and helpfully.\nAlways respond in the same language the customer uses.\nKeep your responses clear and concise.\n\n🔗 CRITICAL - Links & URLs:\n- Always include FULL URLs (e.g., https://fiko.net/pricing)\n- NEVER use placeholders like [link] or [URL]\n- Write complete clickable links in your responses', help_text='⚠️ این فیلد منسوخ شده است (Deprecated).\nاز فیلدهای جدید بالا استفاده کنید.\nاین فیلد فقط برای سازگاری با نسخه\u200cهای قدیم نگه داشته شده.', max_length=5000, null=True, verbose_name='⚠️ [DEPRECATED] Old Auto Prompt'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='دستورات اضافی که در بخش\u200cهای بالا نگنجیده است.\nاین بخش برای نیازهای خاص و منحصر به فرد شماست.\nاگر نیازی ندارید خالی بگذارید.', max_length=2000, null=True, verbose_name='⚡ Custom Instructions (دستورات سفارشی - اختیاری)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='کلید API گوگل جمینای برای سرویس\u200cهای هوش مصنوعی', max_length=200, null=True, verbose_name='🔑 Gemini API Key'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='greeting_rules',
            field=models.TextField(default='⛔ CRITICAL RULE: Say \'سلام\' or \'Hi\' ONLY ONCE per conversation!\n\nWhen you see "SCENARIO: FIRST_MESSAGE":\n→ Greet with customer\'s name ONCE: "سلام [نام]!"\n→ Then answer their question naturally\n\nWhen you see "SCENARIO: WELCOME_BACK":\n→ Say "خوش برگشتی!" ONCE (do NOT say سلام)\n→ Then answer directly\n\nWhen you see "SCENARIO: RECENT_CONVERSATION":\n→ Do NOT greet at all\n→ Answer the question DIRECTLY without any greeting word\n→ Example: "بله، می\u200cتونم کمک کنم..."\n\n⛔ NEVER say "دوباره سلام" or repeat any greeting!', help_text='قوانین برای احوالپرسی و استفاده از نام مشتری.\nشامل: first message greeting, welcome back (12+ hours), no repeat greeting\nجلوگیری از تکرار بیش از حد نام و احوالپرسی\u200cهای مزاحم.', max_length=1000, verbose_name='👋 Greeting & Name Usage (احوالپرسی و استفاده از نام)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='knowledge_limitation_response',
            field=models.TextField(default='متأسفانه این اطلاعات رو ندارم. می\u200cتونم بهت درباره محصولات اصلی\u200cمون کمک کنم، یا می\u200cخوای با تیم پشتیبانی صحبت کنی؟', help_text="پاسخ پیش\u200cفرض وقتی AI اطلاعات ندارد.\nمی\u200cتوانید از placeholder {contact_method} استفاده کنید.\nمثال: 'این اطلاعات رو ندارم، ولی از {contact_method} بپرس'", max_length=500, verbose_name='📢 Knowledge Limitation Response (پاسخ محدودیت دانش)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='language_rules',
            field=models.TextField(default='Always reply in Persian (Farsi).\nConvert Latin names to Persian equivalents (e.g., Omid → امید).\nUse everyday Persian expressions, not formal sentences.', help_text="قوانین زبانی و محلی\u200cسازی را تعریف کنید.\nمثال: 'همیشه به فارسی پاسخ بده'، 'نام\u200cهای لاتین را به فارسی تبدیل کن'\nاین قسمت تعیین می\u200cکند AI چه زبانی و با چه سبکی صحبت کند.", max_length=1000, verbose_name='🌐 Language & Localization'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='link_handling_rules',
            field=models.TextField(default="Always include FULL URLs (e.g., https://example.com/pricing)\nNEVER use placeholders like [link] or [URL]\nIf you don't have a link, say so honestly instead of making one up.", help_text="⚠️ بسیار مهم: قوانین برای ارسال لینک و URL.\nمثال: 'همیشه URL کامل بفرست'، 'هرگز از placeholder مثل [link] استفاده نکن'\nجلوگیری از لینک\u200cهای ناقص یا جعلی.", max_length=500, verbose_name='🔗 Link & URL Handling (مدیریت لینک\u200cها)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='کلید API اوپن\u200cای\u200cآی برای embedding چندزبانه (text-embedding-3-large)', max_length=200, null=True, verbose_name='🔑 OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='response_guidelines',
            field=models.TextField(default='Maximum 600 characters for Instagram compatibility.\nMaximum 3-4 sentences per response.\nLimit emojis to 1 per message.\nAvoid long introductions — go straight to the point.\nIf topic is complex, give a short summary. User can ask for details.\n\n🎯 PERSONALIZATION WITH BIO:\n- If customer has a bio, USE IT in your first response\n- Mention their work/interest naturally to show you understand them\n- Example: "دیدم استراتژیست برندینگ هستی، فیکو برات عالیه!"\n- Convert Latin names to Persian (Omid → امید)\n\n📷🎤 MEDIA MESSAGE RULE:\n- If you see \'[sent an image]:\', the customer SENT an image (not described it)\n- If you see \'[sent a voice message]:\', the customer SENT audio (not typed it)\n- The text after is AI analysis of their media\n- Respond naturally about what they sent, don\'t say \'you described\'', help_text='قوانین اضافی برای فرمت و ساختار پاسخ\u200cها.\nشامل: طول پاسخ (600 کاراکتر برای اینستاگرام)، emoji limit، media rules\nاین بخش جزئیات فرمت پاسخ را کنترل می\u200cکند.', max_length=1000, verbose_name='📝 Response Guidelines (راهنمای پاسخ\u200cدهی)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='response_length',
            field=models.CharField(choices=[('concise', '🔹 Concise (1-2 جمله کوتاه)'), ('moderate', '🔸 Moderate (2-4 جمله متوسط)'), ('detailed', '🔶 Detailed (4+ جمله تفصیلی)')], default='concise', help_text='تعیین کنید پاسخ\u200cهای AI چقدر طولانی باشند.\nکوتاه: برای پیام\u200cهای سریع (مثل اینستاگرام)\nمتوسط: برای توضیحات کلی\nتفصیلی: برای پاسخ\u200cهای کامل و جامع', max_length=20, verbose_name='📏 Response Length (طول پاسخ)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tone_and_style',
            field=models.TextField(default='Speak casually and emotionally, not like a brochure.\nWrite like a person chatting on Instagram.\nKeep responses under 2 short lines.', help_text="لحن و سبک مکالمه AI را تعیین کنید.\nمثال: 'صمیمی و احساسی صحبت کن'، 'مثل یک فرد واقعی در اینستاگرام بنویس'\nاین بخش شخصیت AI را شکل می\u200cدهد.", max_length=1000, verbose_name='💬 Tone & Style (لحن و سبک)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='welcome_back_threshold_hours',
            field=models.IntegerField(default=12, help_text="بعد از چند ساعت، AI باید بگوید 'خوش برگشتی'؟\nپیش\u200cفرض: 12 ساعت\nاگر مشتری بعد از این مدت برگردد، AI می\u200cگوید 'خوش برگشتی!' به جای 'سلام'", verbose_name='⏰ Welcome Back Threshold (ساعت)'),
        ),
    ]
