# Generated by Django 5.1.5 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_affiliationconfig_commission_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='greeting_rules',
            field=models.TextField(default='⛔ CRITICAL RULE: Say \'سلام\' or \'Hi\' ONLY ONCE per conversation!\n\nWhen you see "<greeting_context>FIRST_MESSAGE</greeting_context>":\n→ Greet with customer\'s name ONCE: "سلام [نام]!"\n→ Then answer their question naturally\n\nWhen you see "<greeting_context>WELCOME_BACK_AFTER_*_HOURS</greeting_context>":\n→ Say "خوش برگشتی!" ONCE (do NOT say سلام)\n→ Then answer directly\n\nWhen you see "<greeting_context>RECENT_CONVERSATION_ALREADY_GREETED</greeting_context>":\n→ Do NOT greet at all\n→ Answer the question DIRECTLY without any greeting word\n→ Example: "بله، می\u200cتونم کمک کنم..."\n\n⛔ NEVER say "دوباره سلام" or repeat any greeting!\n⛔ NEVER print the greeting_context tags in your response - they are instructions only!', help_text='قوانین برای احوالپرسی و استفاده از نام مشتری.\nشامل: first message greeting, welcome back (12+ hours), no repeat greeting\nجلوگیری از تکرار بیش از حد نام و احوالپرسی\u200cهای مزاحم.', max_length=1000, verbose_name='👋 Greeting & Name Usage (احوالپرسی و استفاده از نام)'),
        ),
    ]
