# Generated by Django 5.1.5 on 2025-12-12 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_alter_generalsettings_greeting_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPromptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Name of the data field (e.g., 'logo', 'document', 'config')", max_length=255)),
                ('value', models.TextField(blank=True, default='', help_text='Text value of the data field (optional if file is provided)')),
                ('file', models.FileField(blank=True, help_text='File attachment for this data field (e.g., logo, document, PDF)', null=True, upload_to='business_prompt_data/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The BusinessPrompt this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_data', to='settings.businessprompt')),
            ],
            options={
                'verbose_name': '📎 Business Prompt Data',
                'verbose_name_plural': '📎 Business Prompt Data',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'key')},
            },
        ),
    ]
