# Generated by Django 5.1.5 on 2025-08-26 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the website', max_length=255)),
                ('url', models.URLField(help_text='Main URL of the website to crawl')),
                ('description', models.TextField(blank=True, help_text='Optional description of the website')),
                ('max_pages', models.PositiveIntegerField(default=50, help_text='Maximum number of pages to crawl')),
                ('crawl_depth', models.PositiveIntegerField(default=3, help_text='Maximum depth to crawl')),
                ('include_external_links', models.BooleanField(default=False, help_text='Include links to external domains')),
                ('crawl_status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('total_qa_pairs', models.PositiveIntegerField(default=0)),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('crawl_started_at', models.DateTimeField(blank=True, null=True)),
                ('crawl_completed_at', models.DateTimeField(blank=True, null=True)),
                ('crawl_error_message', models.TextField(blank=True)),
                ('crawl_progress', models.FloatField(default=0.0, help_text='Crawl progress percentage (0.0 to 100.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Source',
                'verbose_name_plural': 'Website Sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('raw_content', models.TextField(help_text='Raw HTML content')),
                ('cleaned_content', models.TextField(help_text='Cleaned text content')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the page')),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('h1_tags', models.JSONField(default=list, help_text='List of H1 tags found')),
                ('h2_tags', models.JSONField(default=list, help_text='List of H2 tags found')),
                ('links', models.JSONField(default=list, help_text='List of links found on the page')),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, help_text='Last modified date from HTTP headers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web_knowledge.websitesource')),
            ],
            options={
                'verbose_name': 'Website Page',
                'verbose_name_plural': 'Website Pages',
                'ordering': ['-crawled_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255)),
                ('job_status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('pages_to_crawl', models.PositiveIntegerField(default=0)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('qa_pairs_generated', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_pages', models.JSONField(default=list, help_text='List of URLs that failed to crawl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='web_knowledge.websitesource')),
            ],
            options={
                'verbose_name': 'Crawl Job',
                'verbose_name_plural': 'Crawl Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='AI-generated question')),
                ('answer', models.TextField(help_text='AI-generated answer')),
                ('context', models.TextField(help_text='Source text used to generate the Q&A')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0.0 to 1.0)')),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured Q&A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='web_knowledge.websitepage')),
            ],
            options={
                'verbose_name': 'Q&A Pair',
                'verbose_name_plural': 'Q&A Pairs',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['page', 'generation_status'], name='web_knowled_page_id_f413a9_idx'), models.Index(fields=['confidence_score'], name='web_knowled_confide_5cd8a1_idx'), models.Index(fields=['is_featured'], name='web_knowled_is_feat_a0f425_idx'), models.Index(fields=['created_at'], name='web_knowled_created_9ba7c7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='websitesource',
            index=models.Index(fields=['user', 'crawl_status'], name='web_knowled_user_id_0cbea8_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesource',
            index=models.Index(fields=['created_at'], name='web_knowled_created_bb10e3_idx'),
        ),
        migrations.AddIndex(
            model_name='websitepage',
            index=models.Index(fields=['website', 'processing_status'], name='web_knowled_website_38d02e_idx'),
        ),
        migrations.AddIndex(
            model_name='websitepage',
            index=models.Index(fields=['url'], name='web_knowled_url_2478e5_idx'),
        ),
        migrations.AddIndex(
            model_name='websitepage',
            index=models.Index(fields=['crawled_at'], name='web_knowled_crawled_b5db55_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['website', 'job_status'], name='web_knowled_website_5165f9_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['celery_task_id'], name='web_knowled_celery__a50b00_idx'),
        ),
        migrations.AddIndex(
            model_name='crawljob',
            index=models.Index(fields=['created_at'], name='web_knowled_created_d00388_idx'),
        ),
    ]
