# Generated by Django 5.1.5 on 2025-08-27 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Product or service title', max_length=255)),
                ('product_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('software', 'Software'), ('consultation', 'Consultation'), ('course', 'Course'), ('tool', 'Tool'), ('other', 'Other')], default='product', help_text='Type of product or service', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the product/service')),
                ('link', models.URLField(blank=True, help_text='Link to product page, documentation, or more info')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is currently active')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (optional)', max_digits=10, null=True)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product/Service',
                'verbose_name_plural': 'Products/Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qapair',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('contact', 'Contact'), ('services', 'Services'), ('pricing', 'Pricing'), ('support', 'Support'), ('policies', 'Policies'), ('location', 'Location')], default='general', help_text='Category of the Q&A', max_length=20),
        ),
        migrations.AddField(
            model_name='qapair',
            name='created_by_ai',
            field=models.BooleanField(default=True, help_text='Whether created by AI or manually'),
        ),
        migrations.AddField(
            model_name='qapair',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Manual approval status'),
        ),
        migrations.AddField(
            model_name='qapair',
            name='keywords',
            field=models.JSONField(default=list, help_text='Keywords for search and categorization'),
        ),
        migrations.AddField(
            model_name='qapair',
            name='question_type',
            field=models.CharField(choices=[('factual', 'Factual'), ('procedural', 'Procedural'), ('explanatory', 'Explanatory'), ('comparison', 'Comparison'), ('practical', 'Practical'), ('problem_solving', 'Problem Solving')], default='factual', help_text='Type of question', max_length=20),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['category'], name='web_knowled_categor_e24e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['question_type'], name='web_knowled_questio_7eb441_idx'),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['is_approved'], name='web_knowled_is_appr_0f02cc_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'product_type'], name='web_knowled_user_id_3f2dff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_active'], name='web_knowled_user_id_b188a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='web_knowled_created_001bbe_idx'),
        ),
    ]
