# Generated by Django 5.1.5 on 2025-11-25 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Product or service title', max_length=255)),
                ('product_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('software', 'Software'), ('consultation', 'Consultation'), ('course', 'Course'), ('tool', 'Tool'), ('other', 'Other')], default='product', help_text='Type of product or service', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the product/service')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for listing pages', max_length=500)),
                ('long_description', models.TextField(blank=True, help_text='Extended description with full details')),
                ('link', models.URLField(blank=True, help_text='Link to product page, documentation, or more info')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Current price (used by AI extraction, keep null for manual entry)', max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price (final price after discount, used for manual entry)', max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount in currency', max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('IRR', 'Iranian Rial'), ('IRT', 'Iranian Toman')], default='USD', help_text='Currency code', max_length=3)),
                ('billing_period', models.CharField(blank=True, choices=[('one_time', 'One-time Purchase'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly'), ('daily', 'Daily')], help_text='Billing period for subscriptions', max_length=20, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications (key-value pairs)')),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and search')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='SEO keywords')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is currently active')),
                ('in_stock', models.BooleanField(default=True, help_text='Whether the product is in stock')),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Stock quantity (optional)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Product image file upload', null=True, upload_to='products/images/')),
                ('main_image', models.URLField(blank=True, help_text='URL of main product image')),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO', max_length=500)),
                ('extraction_method', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_auto', 'AI Auto-extracted'), ('ai_assisted', 'AI Assisted')], default='manual', help_text='How this product was created', max_length=20)),
                ('extraction_confidence', models.FloatField(default=1.0, help_text='AI extraction confidence (0-1)')),
                ('extraction_metadata', models.JSONField(blank=True, default=dict, help_text='Extraction metadata (model, timestamp, etc.)')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External product ID (e.g., woo_414, shopify_789)', max_length=100, null=True)),
                ('external_source', models.CharField(blank=True, default='manual', help_text='Source of the product (woocommerce, shopify, manual)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product/Service',
                'verbose_name_plural': 'Products/Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qapair',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('contact', 'Contact'), ('services', 'Services'), ('pricing', 'Pricing'), ('support', 'Support'), ('policies', 'Policies'), ('location', 'Location')], default='general', help_text='Category of the Q&A', max_length=20),
        ),
        migrations.AddField(
            model_name='qapair',
            name='created_by_ai',
            field=models.BooleanField(default=True, help_text='Whether created by AI or manually'),
        ),
        migrations.AddField(
            model_name='qapair',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Manual approval status'),
        ),
        migrations.AddField(
            model_name='qapair',
            name='keywords',
            field=models.JSONField(default=list, help_text='Keywords for search and categorization'),
        ),
        migrations.AddField(
            model_name='qapair',
            name='question_type',
            field=models.CharField(choices=[('factual', 'Factual'), ('procedural', 'Procedural'), ('explanatory', 'Explanatory'), ('comparison', 'Comparison'), ('practical', 'Practical'), ('problem_solving', 'Problem Solving')], default='factual', help_text='Type of question', max_length=20),
        ),
        migrations.AddField(
            model_name='qapair',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='source_type',
            field=models.CharField(choices=[('crawled', 'Crawled'), ('wordpress', 'WordPress Sync')], default='crawled', max_length=20),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='wordpress_post_id',
            field=models.IntegerField(blank=True, help_text='WordPress Post ID if synced', null=True),
        ),
        migrations.AddField(
            model_name='websitesource',
            name='auto_extract_products',
            field=models.BooleanField(default=True, help_text='Automatically extract products/services from crawled pages using AI'),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='context',
            field=models.TextField(blank=True, default='', help_text='Source text used to generate the Q&A'),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Source page (if deleted, Q&A remains)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_pairs', to='web_knowledge.websitepage'),
        ),
        migrations.AlterField(
            model_name='websitesource',
            name='crawl_depth',
            field=models.PositiveIntegerField(default=5, help_text='Maximum depth to crawl'),
        ),
        migrations.AlterField(
            model_name='websitesource',
            name='max_pages',
            field=models.PositiveIntegerField(default=200, help_text='Maximum number of pages to crawl'),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['category'], name='web_knowled_categor_e24e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['question_type'], name='web_knowled_questio_7eb441_idx'),
        ),
        migrations.AddIndex(
            model_name='qapair',
            index=models.Index(fields=['is_approved'], name='web_knowled_is_appr_0f02cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='qapair',
            constraint=models.UniqueConstraint(fields=('page', 'question'), name='unique_question_per_page'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_page',
            field=models.ForeignKey(blank=True, help_text='Source page (if auto-extracted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_products', to='web_knowledge.websitepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_website',
            field=models.ForeignKey(blank=True, help_text='Source website (if auto-extracted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_extracted_products', to='web_knowledge.websitesource'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'product_type'], name='web_knowled_user_id_3f2dff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'is_active'], name='web_knowled_user_id_b188a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='web_knowled_created_001bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['extraction_method'], name='web_knowled_extract_c311a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source_website'], name='web_knowled_source__92778c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'external_source', 'is_active'], name='idx_product_external'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('user', 'external_id'), name='unique_external_product_per_user', violation_error_message='این محصول خارجی قبلاً برای این کاربر وجود دارد'),
        ),
    ]
