# Generated by Django 5.1.5 on 2025-08-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_knowledge', '0002_product_qapair_category_qapair_created_by_ai_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='qapair',
            constraint=models.UniqueConstraint(fields=('page', 'question'), name='unique_question_per_page'),
        ),
    ]
