# Generated by Django 5.1.5 on 2025-08-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_knowledge', '0003_add_unique_question_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qapair',
            name='context',
            field=models.TextField(blank=True, default='', help_text='Source text used to generate the Q&A'),
        ),
        migrations.AlterField(
            model_name='qapair',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='web_knowledge.websitepage'),
        ),
    ]
