# Generated by Django 5.1.5 on 2025-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_knowledge', '0005_qapair_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesource',
            name='max_pages',
            field=models.PositiveIntegerField(default=30, help_text='Maximum number of pages to crawl'),
        ),
    ]
