# Generated by Django 5.1.5 on 2025-10-09 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_knowledge', '0006_alter_websitesource_max_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('one_time', 'One-time Purchase'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('weekly', 'Weekly'), ('daily', 'Daily')], help_text='Billing period for subscriptions', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Product brand', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Product category', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira'), ('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('IRR', 'Iranian Rial'), ('IRT', 'Iranian Toman')], default='USD', help_text='Currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount in currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='extraction_confidence',
            field=models.FloatField(default=1.0, help_text='AI extraction confidence (0-1)'),
        ),
        migrations.AddField(
            model_name='product',
            name='extraction_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extraction metadata (model, timestamp, etc.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='extraction_method',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_auto', 'AI Auto-extracted'), ('ai_assisted', 'AI Assisted')], default='manual', help_text='How this product was created', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of key features'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, help_text='Whether the product is in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='SEO keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Extended description with full details'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(blank=True, help_text='URL of main product image'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for listing pages', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='source_page',
            field=models.ForeignKey(blank=True, help_text='Source page (if auto-extracted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_products', to='web_knowledge.websitepage'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_website',
            field=models.ForeignKey(blank=True, help_text='Source website (if auto-extracted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_extracted_products', to='web_knowledge.websitesource'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Technical specifications (key-value pairs)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, help_text='Stock quantity (optional)', null=True),
        ),
        migrations.AddField(
            model_name='websitesource',
            name='auto_extract_products',
            field=models.BooleanField(default=True, help_text='Automatically extract products/services from crawled pages using AI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current price', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['extraction_method'], name='web_knowled_extract_c311a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source_website'], name='web_knowled_source__92778c_idx'),
        ),
    ]
