# Generated by Django for integrations app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('token_preview', models.CharField(help_text='Safe preview (e.g., wc_sk...abc123)', max_length=20)),
                ('integration_type', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('custom', 'Custom Integration')], max_length=20)),
                ('name', models.CharField(help_text="Friendly name for identification (e.g., 'Main Store')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IPs (empty = all allowed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration (null = never expires)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🔑 Integration Token',
                'verbose_name_plural': '🔑 Integration Tokens',
                'db_table': 'integration_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WooCommerceEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='Unique event ID from WooCommerce (for idempotency)', max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted')], max_length=30)),
                ('woo_product_id', models.IntegerField(help_text='Product ID in WooCommerce')),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('processed_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.integrationtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📝 WooCommerce Event Log',
                'verbose_name_plural': '📝 WooCommerce Event Logs',
                'db_table': 'woocommerce_event_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationtoken',
            index=models.Index(fields=['user', 'integration_type', 'is_active'], name='integration_user_in_5e8f89_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtoken',
            index=models.Index(fields=['token'], name='integration_token_d36f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationtoken',
            index=models.Index(fields=['is_active'], name='integration_is_acti_81e3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceeventlog',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='woocommerce_user_id_e7d1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceeventlog',
            index=models.Index(fields=['event_id'], name='woocommerce_event_i_f7c52a_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceeventlog',
            index=models.Index(fields=['woo_product_id'], name='woocommerce_woo_pro_6f9e83_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceeventlog',
            index=models.Index(fields=['processed_successfully'], name='woocommerce_process_a3b5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='woocommerceeventlog',
            index=models.Index(fields=['created_at'], name='woocommerce_created_d4c8e1_idx'),
        ),
    ]

