# Safe migration that handles existing tables
# Generated by Django 5.1.5 on 2025-11-25 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def safe_create_wordpress_tables(apps, schema_editor):
    """
    Safely create WordPress content tables if they don't already exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if wordpress_content table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'wordpress_content'
            )
        """)
        content_table_exists = cursor.fetchone()[0]
        
        # Check if wordpress_content_event_log table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'wordpress_content_event_log'
            )
        """)
        event_log_table_exists = cursor.fetchone()[0]
        
        # Create wordpress_content table if it doesn't exist
        if not content_table_exists:
            cursor.execute("""
                CREATE TABLE wordpress_content (
                    id UUID PRIMARY KEY,
                    wp_post_id INTEGER NOT NULL,
                    content_type VARCHAR(20) NOT NULL,
                    post_type_slug VARCHAR(50) NOT NULL,
                    title VARCHAR(500) NOT NULL,
                    content TEXT NOT NULL,
                    excerpt TEXT,
                    permalink VARCHAR(200) NOT NULL,
                    author VARCHAR(200),
                    categories JSONB DEFAULT '[]'::jsonb,
                    tags JSONB DEFAULT '[]'::jsonb,
                    featured_image VARCHAR(200),
                    is_published BOOLEAN DEFAULT TRUE,
                    modified_date TIMESTAMP WITH TIME ZONE NOT NULL,
                    content_hash VARCHAR(64) NOT NULL,
                    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    metadata JSONB DEFAULT '{}'::jsonb,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                )
            """)
            print("✅ Created wordpress_content table")
        else:
            print("⏭️  wordpress_content table already exists, skipping")
        
        # Create wordpress_content_event_log table if it doesn't exist
        if not event_log_table_exists:
            # First check if integrations_integrationtoken table exists
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'integrations_integrationtoken'
                )
            """)
            token_table_exists = cursor.fetchone()[0]
            
            # Create table with or without foreign key depending on whether token table exists
            if token_table_exists:
                cursor.execute("""
                    CREATE TABLE wordpress_content_event_log (
                        id UUID PRIMARY KEY,
                        event_id VARCHAR(100) UNIQUE NOT NULL,
                        event_type VARCHAR(30) NOT NULL,
                        wp_post_id INTEGER NOT NULL,
                        payload JSONB NOT NULL,
                        processed_successfully BOOLEAN DEFAULT TRUE,
                        error_message TEXT,
                        processing_time_ms INTEGER,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        token_id UUID REFERENCES integrations_integrationtoken(id) ON DELETE SET NULL,
                        user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                    )
                """)
                print("✅ Created wordpress_content_event_log table with token_id foreign key")
            else:
                cursor.execute("""
                    CREATE TABLE wordpress_content_event_log (
                        id UUID PRIMARY KEY,
                        event_id VARCHAR(100) UNIQUE NOT NULL,
                        event_type VARCHAR(30) NOT NULL,
                        wp_post_id INTEGER NOT NULL,
                        payload JSONB NOT NULL,
                        processed_successfully BOOLEAN DEFAULT TRUE,
                        error_message TEXT,
                        processing_time_ms INTEGER,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        token_id UUID,
                        user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                    )
                """)
                print("✅ Created wordpress_content_event_log table (will add foreign key constraint later)")
        else:
            print("⏭️  wordpress_content_event_log table already exists, skipping")


def safe_create_indexes(apps, schema_editor):
    """
    Safely create indexes if they don't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        indexes_to_create = [
            # WordPressContent indexes
            ("wordpress_c_user_id_748630_idx", "wordpress_content", ["user_id", "content_type", "is_published"]),
            ("wordpress_c_user_id_3e6d89_idx", "wordpress_content", ["user_id", "wp_post_id", "post_type_slug"]),
            ("wordpress_c_permali_e052d8_idx", "wordpress_content", ["permalink"]),
            # WordPressContentEventLog indexes
            ("wordpress_c_user_id_2448eb_idx", "wordpress_content_event_log", ["user_id", "event_type", "created_at"]),
            ("wordpress_c_event_i_ac43a6_idx", "wordpress_content_event_log", ["event_id"]),
        ]
        
        for index_name, table_name, columns in indexes_to_create:
            try:
                # Check if index exists
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE tablename = %s AND indexname = %s
                    )
                """, [table_name, index_name])
                
                if not cursor.fetchone()[0]:
                    cols_str = ", ".join(columns)
                    cursor.execute(f"""
                        CREATE INDEX {index_name} 
                        ON {table_name}({cols_str})
                    """)
                    print(f"✅ Created index {index_name}")
                else:
                    print(f"⏭️  Index {index_name} already exists, skipping")
            except Exception as e:
                print(f"⚠️  Could not create index {index_name}: {e}")


def safe_create_constraints(apps, schema_editor):
    """
    Safely create constraints if they don't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check and create unique constraint for wordpress_content
        try:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'unique_wp_content_per_user'
                )
            """)
            
            if not cursor.fetchone()[0]:
                cursor.execute("""
                    ALTER TABLE wordpress_content
                    ADD CONSTRAINT unique_wp_content_per_user 
                    UNIQUE (user_id, wp_post_id, post_type_slug)
                """)
                print("✅ Created unique constraint unique_wp_content_per_user")
            else:
                print("⏭️  Constraint unique_wp_content_per_user already exists, skipping")
        except Exception as e:
            print(f"⚠️  Could not create constraint: {e}")


def safe_rename_indexes(apps, schema_editor):
    """
    Safely rename indexes if the old ones exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        index_renames = [
            # IntegrationToken indexes
            ("integration_user_in_5e8f89_idx", "integration_user_id_60f601_idx"),
            ("integration_token_d36f5c_idx", "integration_token_018746_idx"),
            ("integration_is_acti_81e3cf_idx", "integration_is_acti_a2cb85_idx"),
            # WooCommerceEventLog indexes
            ("woocommerce_user_id_e7d1ac_idx", "woocommerce_user_id_218bd4_idx"),
            ("woocommerce_event_i_f7c52a_idx", "woocommerce_event_i_f04e5c_idx"),
            ("woocommerce_woo_pro_6f9e83_idx", "woocommerce_woo_pro_258e81_idx"),
            ("woocommerce_process_a3b5f4_idx", "woocommerce_process_a941bb_idx"),
            ("woocommerce_created_d4c8e1_idx", "woocommerce_created_e53638_idx"),
        ]
        
        for old_name, new_name in index_renames:
            try:
                # Check if old index exists
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = %s
                    )
                """, [old_name])
                
                old_exists = cursor.fetchone()[0]
                
                # Check if new index exists
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = %s
                    )
                """, [new_name])
                
                new_exists = cursor.fetchone()[0]
                
                if old_exists and not new_exists:
                    cursor.execute(f"ALTER INDEX {old_name} RENAME TO {new_name}")
                    print(f"✅ Renamed index {old_name} to {new_name}")
                elif new_exists:
                    print(f"⏭️  Index {new_name} already exists, skipping rename")
                else:
                    print(f"⏭️  Index {old_name} doesn't exist, skipping rename")
            except Exception as e:
                print(f"⚠️  Could not rename index {old_name}: {e}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - be careful with this in production!
    """
    pass  # We won't remove tables in reverse to avoid data loss


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create tables safely
        migrations.RunPython(safe_create_wordpress_tables, reverse_migration),
        
        # Create indexes safely
        migrations.RunPython(safe_create_indexes, reverse_migration),
        
        # Create constraints safely
        migrations.RunPython(safe_create_constraints, reverse_migration),
        
        # Rename indexes safely
        migrations.RunPython(safe_rename_indexes, reverse_migration),
    ]
