# Generated by Django 5.1.5 on 2025-11-25 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_wordpresscontent_wordpresscontenteventlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wp_post_id', models.IntegerField(help_text='Post ID in WordPress')),
                ('content_type', models.CharField(choices=[('page', 'صفحه'), ('post', 'نوشته'), ('custom', 'سفارشی')], max_length=20)),
                ('post_type_slug', models.CharField(help_text='WordPress post type (page, post, event, ...)', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Full content (HTML stripped)')),
                ('excerpt', models.TextField(blank=True)),
                ('permalink', models.URLField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('categories', models.JSONField(default=list, help_text='Post categories')),
                ('tags', models.JSONField(default=list, help_text='Post tags')),
                ('featured_image', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('modified_date', models.DateTimeField(help_text='Last modified in WordPress')),
                ('content_hash', models.CharField(help_text='SHA256 hash of content for change detection', max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra WordPress metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '📄 WordPress Content',
                'verbose_name_plural': '📄 WordPress Content',
                'db_table': 'wordpress_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordPressContentEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('page.created', 'Page Created'), ('page.updated', 'Page Updated'), ('page.deleted', 'Page Deleted'), ('post.created', 'Post Created'), ('post.updated', 'Post Updated'), ('post.deleted', 'Post Deleted')], max_length=30)),
                ('wp_post_id', models.IntegerField()),
                ('payload', models.JSONField()),
                ('processed_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '📝 WordPress Content Event',
                'verbose_name_plural': '📝 WordPress Content Events',
                'db_table': 'wordpress_content_event_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='integrationtoken',
            new_name='integration_user_id_60f601_idx',
            old_name='integration_user_in_5e8f89_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationtoken',
            new_name='integration_token_018746_idx',
            old_name='integration_token_d36f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationtoken',
            new_name='integration_is_acti_a2cb85_idx',
            old_name='integration_is_acti_81e3cf_idx',
        ),
        migrations.RenameIndex(
            model_name='woocommerceeventlog',
            new_name='woocommerce_user_id_218bd4_idx',
            old_name='woocommerce_user_id_e7d1ac_idx',
        ),
        migrations.RenameIndex(
            model_name='woocommerceeventlog',
            new_name='woocommerce_event_i_f04e5c_idx',
            old_name='woocommerce_event_i_f7c52a_idx',
        ),
        migrations.RenameIndex(
            model_name='woocommerceeventlog',
            new_name='woocommerce_woo_pro_258e81_idx',
            old_name='woocommerce_woo_pro_6f9e83_idx',
        ),
        migrations.RenameIndex(
            model_name='woocommerceeventlog',
            new_name='woocommerce_process_a941bb_idx',
            old_name='woocommerce_process_a3b5f4_idx',
        ),
        migrations.RenameIndex(
            model_name='woocommerceeventlog',
            new_name='woocommerce_created_e53638_idx',
            old_name='woocommerce_created_d4c8e1_idx',
        ),
        migrations.AddField(
            model_name='wordpresscontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordpresscontenteventlog',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_events', to='integrations.integrationtoken'),
        ),
        migrations.AddField(
            model_name='wordpresscontenteventlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_content_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wordpresscontent',
            index=models.Index(fields=['user', 'content_type', 'is_published'], name='wordpress_c_user_id_748630_idx'),
        ),
        migrations.AddIndex(
            model_name='wordpresscontent',
            index=models.Index(fields=['user', 'wp_post_id', 'post_type_slug'], name='wordpress_c_user_id_3e6d89_idx'),
        ),
        migrations.AddIndex(
            model_name='wordpresscontent',
            index=models.Index(fields=['permalink'], name='wordpress_c_permali_e052d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='wordpresscontent',
            constraint=models.UniqueConstraint(fields=('user', 'wp_post_id', 'post_type_slug'), name='unique_wp_content_per_user'),
        ),
        migrations.AddIndex(
            model_name='wordpresscontenteventlog',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='wordpress_c_user_id_2448eb_idx'),
        ),
        migrations.AddIndex(
            model_name='wordpresscontenteventlog',
            index=models.Index(fields=['event_id'], name='wordpress_c_event_i_ac43a6_idx'),
        ),
    ]
