# Generated by Django 5.2.1 on 2025-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='message.tag'),
        ),
    ]
