# Generated by Django 5.2.1 on 2025-06-03 13:50

import message.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_customer_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(default=message.models.generate_short_uuid, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=message.models.generate_short_uuid, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
