# Generated by Django 5.2.1 on 2025-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
