# Generated by Django 5.1.5 on 2025-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_add_username_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata for the message (e.g., AI response metadata)', null=True),
        ),
    ]
