# Generated by Django 5.1.5 on 2025-10-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_add_metadata_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(choices=[('none', 'No feedback'), ('positive', '👍 Positive'), ('negative', '👎 Negative')], default='none', help_text='Customer feedback on AI response quality', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='feedback_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when feedback was submitted', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='feedback_comment',
            field=models.TextField(blank=True, default='', help_text='Optional comment from customer about the response', max_length=500),
        ),
    ]
