# Generated by Django 5.1.5 on 2025-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_message_feedback_message_feedback_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.IntegerField(blank=True, help_text='Number of input tokens used (for AI responses)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.IntegerField(blank=True, help_text='Number of output tokens generated (for AI responses)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='Total tokens used (input + output)', null=True),
        ),
    ]
