# Generated by Django 5.1.5 on 2025-10-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_message_input_tokens_message_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, help_text="User's biography from Instagram (only for Instagram source, Business accounts)", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='persona_data',
            field=models.JSONField(blank=True, help_text='Auto-extracted persona info from bio: interests, tone_preference, profession', null=True),
        ),
    ]
