# Generated by Django 5.1.5 on 2025-10-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_conversation_intercom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='intercom_conversation_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sync_to_intercom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='intercom_message_id',
        ),
    ]
