# Generated by Django 5.1.5 on 2025-10-19 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_remove_conversation_intercom_conversation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, help_text='Downloaded media file (voice/image)', null=True, upload_to='message_media/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, help_text='External media URL from platform', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message'), ('image', 'Image Message'), ('video', 'Video Message')], default='text', help_text='Type of message content', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When media processing completed', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_duration_ms',
            field=models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed')], default='completed', help_text='Media processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='transcription',
            field=models.TextField(blank=True, help_text='Voice transcription or image description', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
