# Generated by Django 5.1.5 on 2025-11-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_message_media_file_message_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='buttons',
            field=models.JSONField(blank=True, help_text="CTA buttons for this message (Instagram/WhatsApp Button Template). Max 3 buttons. Format: [{'type': 'web_url', 'title': 'عنوان', 'url': 'https://...'}]", null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message'), ('image', 'Image Message'), ('video', 'Video Message'), ('share', 'Post/Reel Share')], default='text', help_text='Type of message content', max_length=20),
        ),
    ]
