# Generated by Django 5.1.5 on 2025-12-12 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_message_buttons_alter_message_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value data for this customer. Format: {"key1": "value1", "key2": "value2"}', null=True),
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Name of the data field (e.g., 'birthday', 'company', 'notes', 'contract')", max_length=255)),
                ('value', models.TextField(blank=True, default='', help_text='Text value of the data field (optional if file is provided)')),
                ('file', models.FileField(blank=True, help_text='File attachment for this data field (e.g., contract, ID card, document)', null=True, upload_to='customer_data/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_data', to='message.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Data',
                'verbose_name_plural': 'Customer Data',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'user', 'key')},
            },
        ),
    ]
