# Generated by Django 5.1.5 on 2025-08-03 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-1.5-flash', help_text='Gemini model to use', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Response creativity (0.0-1.0)')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Maximum tokens in response')),
                ('auto_response_enabled', models.BooleanField(default=True, help_text='Enable automatic responses')),
                ('response_delay_seconds', models.IntegerField(default=2, help_text='Delay before auto response')),
                ('business_hours_only', models.BooleanField(default=False, help_text='Only respond during business hours')),
                ('business_start_time', models.TimeField(default='09:00', help_text='Business start time')),
                ('business_end_time', models.TimeField(default='17:00', help_text='Business end time')),
                ('timezone', models.CharField(default='UTC', help_text='Business timezone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '⚙️ AI Model Config',
                'verbose_name_plural': '⚙️ AI Model Configs',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_identifier', models.CharField(help_text='Customer ID or email or phone', max_length=255)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('customer_metadata', models.JSONField(blank=True, default=dict, help_text='Customer info like name, preferences, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The business owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '💬 Chat Session',
                'verbose_name_plural': '💬 Chat Sessions',
                'unique_together': {('user', 'customer_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('customer', 'Customer Message'), ('ai', 'AI Response'), ('system', 'System Message')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message data')),
                ('gemini_response_data', models.JSONField(blank=True, help_text='Raw Gemini API response', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='AI response time in milliseconds', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in response', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AI_model.chatsession')),
            ],
            options={
                'verbose_name': '💬 Chat Message',
                'verbose_name_plural': '💬 Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_prompt_tokens', models.IntegerField(default=0)),
                ('total_completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_response_time_ms', models.BigIntegerField(default=0)),
                ('average_response_time_ms', models.FloatField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📊 AI Usage Tracking',
                'verbose_name_plural': '📊 AI Usage Tracking',
                'indexes': [models.Index(fields=['user', 'date'], name='AI_model_ai_user_id_003df3_idx'), models.Index(fields=['date'], name='AI_model_ai_date_77aac8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('ai_responses', models.IntegerField(default=0)),
                ('customer_messages', models.IntegerField(default=0)),
                ('average_response_time_ms', models.FloatField(blank=True, null=True)),
                ('customer_satisfaction_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📊 Chat Analytics',
                'verbose_name_plural': '📊 Chat Analytics',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
