# Generated by Django 5.1.5 on 2025-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-1.5-flash', help_text='Gemini model to use', max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Response creativity (0.0-1.0)')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Maximum tokens in response')),
                ('auto_response_enabled', models.BooleanField(default=True, help_text='Enable automatic responses globally')),
                ('response_delay_seconds', models.IntegerField(default=2, help_text='Delay before auto response')),
                ('business_hours_only', models.BooleanField(default=False, help_text='Only respond during business hours')),
                ('business_start_time', models.TimeField(default='09:00', help_text='Business start time')),
                ('business_end_time', models.TimeField(default='17:00', help_text='Business end time')),
                ('timezone', models.CharField(default='UTC', help_text='Business timezone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🤖 AI Global Config',
                'verbose_name_plural': '🤖 AI Global Config',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatanalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatanalytics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIModelConfig',
        ),
        migrations.DeleteModel(
            name='ChatAnalytics',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
