# Generated by Django 5.1.5 on 2025-10-07 21:12

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0002_aiglobalconfig_alter_chatanalytics_unique_together_and_more'),
        ('message', '0009_message_input_tokens_message_output_tokens_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable pgvector extension first
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
        migrations.CreateModel(
            name='IntentRouting',
            fields=[
                ('intent', models.CharField(choices=[('pricing', 'Pricing & Plans'), ('product', 'Product Info'), ('howto', 'How-to & Tutorial'), ('contact', 'Contact & Support'), ('general', 'General Question')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('primary_source', models.CharField(choices=[('faq', 'FAQ'), ('manual', 'Manual Prompt'), ('products', 'Products'), ('website', 'Website')], max_length=20)),
                ('secondary_sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Comma-separated list of secondary sources', size=None)),
                ('primary_token_budget', models.IntegerField(default=800, help_text='Max tokens for primary source (default: 800)')),
                ('secondary_token_budget', models.IntegerField(default=300, help_text='Max tokens for secondary sources (default: 300)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🧭 Intent Routing',
                'verbose_name_plural': '🧭 Intent Routing',
                'db_table': 'intent_routing',
            },
        ),
        migrations.CreateModel(
            name='IntentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('pricing', 'Pricing & Plans'), ('product', 'Product Info'), ('howto', 'How-to & Tutorial'), ('contact', 'Contact & Support'), ('general', 'General Question')], db_index=True, max_length=20)),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar', 'العربية'), ('tr', 'Türkçe')], db_index=True, max_length=5)),
                ('keyword', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0, help_text='Keyword importance (0.1-3.0). Higher = more important')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for global keywords', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🔑 Intent Keyword',
                'verbose_name_plural': '🔑 Intent Keywords',
                'db_table': 'intent_keywords',
                'indexes': [models.Index(fields=['intent', 'language', 'is_active'], name='intent_keyw_intent_fa7dd2_idx'), models.Index(fields=['user', 'is_active'], name='intent_keyw_user_id_06552d_idx')],
                'unique_together': {('intent', 'language', 'keyword', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SessionMemory',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session_memory', serialize=False, to='message.conversation')),
                ('cumulative_summary', models.TextField(blank=True, default='', help_text='Rolling summary of entire conversation (target: ≤150 tokens)')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages at last summary update')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🧠 Session Memory',
                'verbose_name_plural': '🧠 Session Memories',
                'db_table': 'session_memory',
                'indexes': [models.Index(fields=['user', 'last_updated'], name='session_mem_user_id_a477f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_type', models.CharField(choices=[('faq', 'FAQ'), ('manual', 'Manual Prompt'), ('product', 'Product'), ('website', 'Website Page')], db_index=True, max_length=20)),
                ('source_id', models.UUIDField(blank=True, help_text='Reference to original FAQ/Product/WebsitePage ID', null=True)),
                ('document_id', models.UUIDField(blank=True, db_index=True, help_text='Group chunks from same document', null=True)),
                ('section_title', models.TextField(blank=True, help_text='Section or paragraph title', null=True)),
                ('full_text', models.TextField(help_text='Full chunk text')),
                ('tldr', models.TextField(blank=True, help_text='TL;DR summary (80-120 words) for efficient retrieval', null=True)),
                ('tldr_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('full_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('language', models.CharField(blank=True, help_text='fa, en, ar, tr', max_length=5, null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '📚 Tenant Knowledge (RAG)',
                'verbose_name_plural': '📚 Tenant Knowledge (RAG)',
                'db_table': 'tenant_knowledge',
                'indexes': [models.Index(fields=['user', 'chunk_type'], name='tenant_know_user_id_a1e630_idx'), models.Index(fields=['user', 'document_id'], name='tenant_know_user_id_1f468a_idx'), models.Index(fields=['created_at'], name='tenant_know_created_5c0997_idx')],
            },
        ),
    ]
