# Generated by Django 5.1.5 on 2025-10-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0004_aiusagelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_user_id_a17394_idx',
            old_name='ai_usage_l_user_id_2a5e9d_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_user_id_5ea126_idx',
            old_name='ai_usage_l_user_id_f7c8a2_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_section_7749f2_idx',
            old_name='ai_usage_l_section_8d3b1f_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_created_aa64d8_idx',
            old_name='ai_usage_l_created_2c4e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_success_d152fc_idx',
            old_name='ai_usage_l_success_9f6d3b_idx',
        ),
    ]
