# Generated by Django 5.1.5 on 2025-11-27 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0009_add_parent_child_chunks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantknowledge',
            name='ai_model_te_documen_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantknowledge',
            name='ai_model_te_parent_idx',
        ),
        migrations.RemoveField(
            model_name='tenantknowledge',
            name='chunk_index',
        ),
        migrations.RemoveField(
            model_name='tenantknowledge',
            name='parent_chunk_id',
        ),
        migrations.AddConstraint(
            model_name='tenantknowledge',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('user', 'source_id', 'chunk_type'), name='unique_chunk_per_source', violation_error_message='این صفحه قبلاً chunk شده است'),
        ),
    ]
