# Generated by Django 5.1.5 on 2025-12-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0010_remove_tenantknowledge_ai_model_te_documen_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiglobalconfig',
            name='model_name',
            field=models.CharField(default='gemini-flash-latest', help_text='Gemini model to use', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='model_name',
            field=models.CharField(blank=True, default='gemini-flash-latest', help_text='AI model used (e.g., gemini-flash-latest, gpt-4)', max_length=100),
        ),
    ]
