# Generated by Django 5.1.5 on 2025-10-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0010_add_unique_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantknowledge',
            name='ai_model_te_documen_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenantknowledge',
            name='ai_model_te_parent_idx',
        ),
        migrations.RemoveField(
            model_name='tenantknowledge',
            name='chunk_index',
        ),
        migrations.RemoveField(
            model_name='tenantknowledge',
            name='parent_chunk_id',
        ),
    ]
