# Generated by Django 5.2.1 on 2025-06-02 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=256, null=True)),
                ('authority', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
