# Generated by Django 5.1.5 on 2025-09-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptionplan_alter_purchases_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tokens_included', models.IntegerField()),
                ('duration_days', models.IntegerField(help_text='Duration of the plan in days')),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('price_en', models.DecimalField(decimal_places=2, help_text='Price displayed for English', max_digits=10)),
                ('price_tr', models.DecimalField(decimal_places=2, help_text='Price displayed for Turkish', max_digits=10)),
                ('price_ar', models.DecimalField(decimal_places=2, help_text='Price displayed for Arabic', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_yearly', 'price_en'],
            },
        ),
        migrations.CreateModel(
            name='TokenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tokens_included', models.IntegerField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for purchase')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.fullplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='full_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.fullplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='token_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.tokenplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='token_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.tokenplan'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
