# Generated by Django 5.1.5 on 2025-11-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_wallettransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='billing_wal_user_id_a4616c_idx',
            old_name='billing_wal_user_id_e7c8b5_idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='billing_wal_related_95216c_idx',
            old_name='billing_wal_related_a5c9d2_idx',
        ),
    ]
