# Generated by Django 5.1.5 on 2025-12-02 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_billing_wal_user_id_e7c8b5_idx_billing_wal_user_id_a4616c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name for banking', max_length=100)),
                ('last_name', models.CharField(help_text='Last name for banking', max_length=100)),
                ('sheba_number', models.CharField(help_text='IBAN/Sheba number for bank transfers', max_length=26)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this billing information', on_delete=django.db.models.deletion.CASCADE, related_name='billing_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '💳 Billing Information',
                'verbose_name_plural': '💳 Billing Information',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to withdraw in Tomans', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of withdrawal request', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date when withdrawal was requested')),
                ('processed_date', models.DateTimeField(blank=True, help_text='Date when withdrawal was processed/paid', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this withdrawal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet_transaction', models.OneToOneField(blank=True, help_text='Related wallet transaction for this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='billing.wallettransaction')),
            ],
            options={
                'verbose_name': '💸 Withdraw Request',
                'verbose_name_plural': '💸 Withdraw Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_wit_user_id_5d54a3_idx'), models.Index(fields=['status', '-created_at'], name='billing_wit_status_42f780_idx')],
            },
        ),
    ]
