# Generated by Django 5.1.5 on 2025-09-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_fullplan_tokenplan_remove_payment_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenplan',
            options={'ordering': ['price_en']},
        ),
        migrations.RemoveField(
            model_name='tokenplan',
            name='price',
        ),
        migrations.AddField(
            model_name='tokenplan',
            name='price_ar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price displayed for Arabic', max_digits=10),
        ),
        migrations.AddField(
            model_name='tokenplan',
            name='price_en',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price displayed for English', max_digits=10),
        ),
        migrations.AddField(
            model_name='tokenplan',
            name='price_tr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price displayed for Turkish', max_digits=10),
        ),
    ]
