# Generated by Django 5.1.5 on 2025-12-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billinginformation_withdraw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAffiliateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of payment amount user earns when their referral makes a payment', max_digits=5, verbose_name='Direct Commission %')),
                ('direct_validity_days', models.PositiveIntegerField(default=30, help_text='Days after referral registration during which payments qualify for direct commission (0 = unlimited)', verbose_name='Direct Commission Validity (Days)')),
                ('upline_commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text="Percentage of referral's affiliate earnings that user receives (multi-level)", max_digits=5, verbose_name='Upline Commission %')),
                ('upline_validity_days', models.PositiveIntegerField(default=365, help_text='Days during which upline commissions apply from when referral joined (0 = unlimited)', verbose_name='Upline Commission Validity (Days)')),
                ('is_active', models.BooleanField(default=True, help_text="Enable/disable this user's custom affiliate rule", verbose_name='Rule Active')),
                ('notes', models.TextField(blank=True, help_text="Internal notes about this user's affiliate arrangement", verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🎯 User Affiliate Rule',
                'verbose_name_plural': '🎯 User Affiliate Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='commission_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 - Direct'), (2, 'Level 2 - Upline')], help_text="Commission level: 1=Direct (from referral's payment), 2=Upline (from referral's commission)", null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage applied for this transaction', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount the commission was calculated from', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source_commission',
            field=models.ForeignKey(blank=True, help_text='For upline commissions: the direct commission that triggered this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upline_commissions', to='billing.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('commission', 'Affiliate Commission'), ('upline_commission', 'Upline Commission'), ('payment', 'Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Manual Adjustment')], default='commission', max_length=20),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='billing_wal_transac_124cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['commission_level'], name='billing_wal_commiss_104295_idx'),
        ),
        migrations.AddField(
            model_name='useraffiliaterule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created/modified this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affiliate_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraffiliaterule',
            name='user',
            field=models.OneToOneField(help_text='User who receives these affiliate commission settings', on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_rule', to=settings.AUTH_USER_MODEL),
        ),
    ]
