# Generated by Django 5.1.5 on 2025-10-07 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='queued_full_plan',
            field=models.ForeignKey(blank=True, help_text='Full plan scheduled to activate at end_date of current plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_subscriptions', to='billing.fullplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='queued_token_plan',
            field=models.ForeignKey(blank=True, help_text='Token plan scheduled to activate at end_date of current plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_subscriptions', to='billing.tokenplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='queued_tokens_amount',
            field=models.IntegerField(blank=True, help_text='Number of tokens to be added when queued plan activates', null=True),
        ),
    ]
