# Generated by Django 5.1.5 on 2025-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_change_price_to_single_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the plan', max_digits=10),
        ),
    ]
