# Generated by Django 5.1.5 on 2025-11-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_fullplan_price'),
        ('billing', '0010_change_price_to_integer'),
    ]

    operations = [
    ]
