# Generated by Django 5.1.5 on 2025-11-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_merge_20251105_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0, help_text='Amount in Toman'),
        ),
    ]
