# Generated by Django 5.1.5 on 2025-11-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullplan',
            name='price',
            field=models.IntegerField(default=0, help_text='Price of the plan'),
        ),
    ]
