# Generated by Django 5.1.5 on 2025-09-30 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('en', 'English'), ('fa', 'Persian (فارسی)'), ('ar', 'Arabic (العربية)'), ('tr', 'Turkish (Türkçe)'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], help_text='Language code', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Language name', max_length=100)),
                ('native_name', models.CharField(blank=True, help_text='Native language name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Type name', max_length=100)),
                ('code', models.CharField(choices=[('customer_service', 'Customer Service'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Support'), ('onboarding', 'Onboarding'), ('follow_up', 'Follow Up'), ('survey', 'Survey'), ('notification', 'Notification'), ('automation', 'Automation'), ('lead_generation', 'Lead Generation'), ('retention', 'Customer Retention'), ('feedback', 'Feedback Collection'), ('appointment', 'Appointment Booking'), ('payment', 'Payment Processing'), ('other', 'Other')], help_text='Type code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Type description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Color code for UI', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('jsonfield', models.JSONField(default=dict, help_text='Template configuration in JSON format')),
                ('is_active', models.BooleanField(default=True, help_text='Whether template is active')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether template is featured')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('tags', models.JSONField(default=list, help_text='Template tags for categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(help_text='Template language', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workflow_template.language')),
                ('type', models.ForeignKey(help_text='Template type', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workflow_template.type')),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['language', 'type'], name='workflow_te_languag_f6614a_idx'), models.Index(fields=['is_active', 'is_featured'], name='workflow_te_is_acti_809544_idx'), models.Index(fields=['created_at'], name='workflow_te_created_37d10e_idx')],
            },
        ),
    ]
