# Generated by Django 5.1.5 on 2025-11-25 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Tag description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workflow Template', 'verbose_name_plural': 'Workflow Templates'},
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='workflow_te_is_acti_809544_idx',
        ),
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
        migrations.RemoveField(
            model_name='language',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='template',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='type',
            name='code',
        ),
        migrations.RemoveField(
            model_name='type',
            name='color',
        ),
        migrations.RemoveField(
            model_name='type',
            name='icon',
        ),
        migrations.AddField(
            model_name='template',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the template', null=True, upload_to='workflow_templates/covers/'),
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('popular', 'Popular'), ('none', 'None')], default='none', help_text='Template status (New, Popular, or None)', max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Language name', max_length=200),
        ),
        migrations.AlterField(
            model_name='template',
            name='jsonfield',
            field=models.JSONField(blank=True, default=dict, help_text='Template configuration in JSON format'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name', max_length=500),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Type name', max_length=500),
        ),
        migrations.AddField(
            model_name='template',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Template tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='workflow_template.tag'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='workflow_te_is_acti_7c9f68_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['status'], name='workflow_te_status_12a6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['tag'], name='workflow_te_tag_id_7a8470_idx'),
        ),
    ]
