# Generated by Django 5.1.5 on 2025-09-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
        migrations.RemoveField(
            model_name='language',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='code',
        ),
        migrations.RemoveField(
            model_name='type',
            name='color',
        ),
        migrations.RemoveField(
            model_name='type',
            name='icon',
        ),
    ]
