# Generated by Django 5.1.5 on 2025-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0002_remove_language_code_remove_language_native_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Language name', max_length=200),
        ),
        migrations.AlterField(
            model_name='template',
            name='jsonfield',
            field=models.JSONField(blank=True, default=dict, help_text='Template configuration in JSON format'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name', max_length=500),
        ),
        migrations.AlterField(
            model_name='template',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Template tags for categorization'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Type name', max_length=500),
        ),
    ]
