# Generated by Django 5.1.5 on 2025-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0003_alter_language_name_alter_template_jsonfield_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workflow Template', 'verbose_name_plural': 'Workflow Templates'},
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='workflow_te_is_acti_809544_idx',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='template',
            name='usage_count',
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='workflow_te_is_acti_7c9f68_idx'),
        ),
    ]
