# Generated by Django 5.1.5 on 2025-10-01 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_template', '0004_alter_template_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Tag description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the template', null=True, upload_to='workflow_templates/covers/'),
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('popular', 'Popular'), ('none', 'None')], default='none', help_text='Template status (New, Popular, or None)', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Template tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='workflow_template.tag'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['status'], name='workflow_te_status_12a6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['tag'], name='workflow_te_tag_id_7a8470_idx'),
        ),
    ]
