# Generated by Django 5.2.1 on 2025-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_reply_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('AI', 'AI')], default='Manual', max_length=20),
        ),
    ]
