# Generated by Django 5.1.5 on 2025-08-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_default_reply_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wizard_complete',
            field=models.BooleanField(default=False),
        ),
    ]
