# Generated by Django 5.1.5 on 2025-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_wizard_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_reply_handler',
            field=models.CharField(choices=[('Manual', 'Manual'), ('AI', 'AI')], default='AI', max_length=20),
        ),
    ]
