# Generated by Django 5.1.5 on 2025-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
    ]
