# Generated by Django 5.1.5 on 2025-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_google_avatar_url_user_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('ecommerce', 'E-commerce'), ('restaurant', 'Restaurant'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('technology', 'Technology'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('travel', 'Travel & Tourism'), ('beauty', 'Beauty & Wellness'), ('fitness', 'Fitness & Sports'), ('automotive', 'Automotive'), ('consulting', 'Consulting'), ('legal', 'Legal Services'), ('nonprofit', 'Non-profit'), ('manufacturing', 'Manufacturing'), ('agriculture', 'Agriculture'), ('entertainment', 'Entertainment'), ('media', 'Media & Publishing'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
