# Generated by Django 5.1.5 on 2025-12-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_affiliate_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
