# Generated by Django 5.1.5 on 2025-12-05 17:43

from django.db import migrations, models


def clear_old_tokens(apps, schema_editor):
    """
    Clear old 6-digit tokens before changing column size to 4.
    These are temporary verification tokens, so it's safe to delete them.
    Users will simply need to request new codes.
    """
    EmailConfirmationToken = apps.get_model('accounts', 'EmailConfirmationToken')
    OTPToken = apps.get_model('accounts', 'OTPToken')
    
    # Delete all existing tokens (they have 6-digit codes that won't fit)
    EmailConfirmationToken.objects.all().delete()
    OTPToken.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_affiliate_active'),
    ]

    operations = [
        # First, clear existing tokens with 6-digit codes
        migrations.RunPython(clear_old_tokens, migrations.RunPython.noop),
        
        # Now safe to change column size
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
