# Generated by Django 5.1.5 on 2025-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
