# Safe migration that handles existing columns
# Generated by Django 5.1.5 on 2025-11-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def safe_add_fields(apps, schema_editor):
    """
    Safely add fields if they don't already exist.
    This prevents errors when columns are already present in production.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Get existing columns for accounts_user table
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='accounts_user' AND table_schema='public'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Add email_confirmed if it doesn't exist
        if 'email_confirmed' not in existing_columns:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ADD COLUMN email_confirmed BOOLEAN DEFAULT FALSE NOT NULL
            """)
            print("✅ Added email_confirmed column")
        else:
            print("⏭️  email_confirmed column already exists, skipping")
        
        # Add invite_code if it doesn't exist
        if 'invite_code' not in existing_columns:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ADD COLUMN invite_code VARCHAR(20) NULL UNIQUE
            """)
            print("✅ Added invite_code column")
        else:
            print("⏭️  invite_code column already exists, skipping")
        
        # Add wallet_balance if it doesn't exist
        if 'wallet_balance' not in existing_columns:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ADD COLUMN wallet_balance NUMERIC(10, 2) DEFAULT 0.00 NOT NULL
            """)
            print("✅ Added wallet_balance column")
        else:
            print("⏭️  wallet_balance column already exists, skipping")
        
        # Add referred_by_id if it doesn't exist
        if 'referred_by_id' not in existing_columns:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ADD COLUMN referred_by_id BIGINT NULL
            """)
            # Create foreign key constraint
            try:
                cursor.execute("""
                    ALTER TABLE accounts_user 
                    ADD CONSTRAINT accounts_user_referred_by_id_fkey 
                    FOREIGN KEY (referred_by_id) 
                    REFERENCES accounts_user(id) 
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED
                """)
            except Exception as e:
                print(f"⚠️  Foreign key constraint may already exist: {e}")
            
            # Create index for foreign key
            try:
                cursor.execute("""
                    CREATE INDEX accounts_user_referred_by_id_idx 
                    ON accounts_user(referred_by_id)
                """)
            except Exception as e:
                print(f"⚠️  Index may already exist: {e}")
            
            print("✅ Added referred_by_id column with foreign key")
        else:
            print("⏭️  referred_by_id column already exists, skipping")


def safe_alter_fields(apps, schema_editor):
    """
    Safely alter fields
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Alter business_type field if needed
        try:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ALTER COLUMN business_type TYPE VARCHAR(1000)
            """)
            print("✅ Altered business_type column")
        except Exception as e:
            print(f"⏭️  business_type column already correct or error: {e}")
        
        # Alter phone_number field if needed
        try:
            cursor.execute("""
                ALTER TABLE accounts_user 
                ALTER COLUMN phone_number TYPE VARCHAR(100)
            """)
            # Add unique constraint if it doesn't exist
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name='accounts_user' 
                AND constraint_type='UNIQUE' 
                AND constraint_name='accounts_user_phone_number_key'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE accounts_user 
                    ADD CONSTRAINT accounts_user_phone_number_key 
                    UNIQUE (phone_number)
                """)
            print("✅ Altered phone_number column")
        except Exception as e:
            print(f"⏭️  phone_number column already correct or error: {e}")


def create_email_confirmation_token_table(apps, schema_editor):
    """
    Create EmailConfirmationToken table if it doesn't exist
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'accounts_emailconfirmationtoken'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            cursor.execute("""
                CREATE TABLE accounts_emailconfirmationtoken (
                    id BIGSERIAL PRIMARY KEY,
                    code VARCHAR(6) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    is_used BOOLEAN NOT NULL DEFAULT FALSE,
                    user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE
                )
            """)
            cursor.execute("""
                CREATE INDEX accounts_emailconfirmationtoken_user_id_idx 
                ON accounts_emailconfirmationtoken(user_id)
            """)
            print("✅ Created EmailConfirmationToken table")
        else:
            print("⏭️  EmailConfirmationToken table already exists, skipping")


def create_otp_token_table(apps, schema_editor):
    """
    Create OTPToken table if it doesn't exist
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'accounts_otptoken'
            )
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            cursor.execute("""
                CREATE TABLE accounts_otptoken (
                    id BIGSERIAL PRIMARY KEY,
                    phone_number VARCHAR(100) NOT NULL,
                    code VARCHAR(6) NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    is_used BOOLEAN NOT NULL DEFAULT FALSE,
                    attempts INTEGER NOT NULL DEFAULT 0
                )
            """)
            cursor.execute("""
                CREATE INDEX accounts_ot_phone_n_0ab878_idx 
                ON accounts_otptoken(phone_number, created_at DESC)
            """)
            print("✅ Created OTPToken table")
        else:
            print("⏭️  OTPToken table already exists, skipping")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - be careful with this in production!
    """
    pass  # We won't remove columns/tables in reverse to avoid data loss


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_business_type'),
    ]

    operations = [
        # First, add the new fields
        migrations.RunPython(safe_add_fields, reverse_migration),
        
        # Then, alter existing fields
        migrations.RunPython(safe_alter_fields, reverse_migration),
        
        # Create EmailConfirmationToken table
        migrations.RunPython(create_email_confirmation_token_table, reverse_migration),
        
        # Create OTPToken table
        migrations.RunPython(create_otp_token_table, reverse_migration),
    ]
