# Generated by Django 5.1.5 on 2025-12-08 09:40

import accounts.models.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_change_otp_code_to_4_digits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateUserSummary',
            fields=[
            ],
            options={
                'verbose_name': '📊 Affiliate Summary',
                'verbose_name_plural': '📊 Affiliate Summaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.user_manager.UserManager()),
            ],
        ),
    ]
