# Generated by Django 5.1.5 on 2025-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_affiliateusersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_correct',
            field=models.BooleanField(default=False, help_text='Whether the user has set a valid password (False for OTP-only registrations)', verbose_name='Password Set'),
        ),
    ]
