# Generated by Django 5.1.5 on 2025-12-09 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_pass_correct_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_password', models.CharField(max_length=255, verbose_name='Plain Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pass', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🔑 User Password',
                'verbose_name_plural': '🔑 User Passwords',
            },
        ),
    ]
