# Generated by Django 5.1.5 on 2025-11-25 10:10
# Merge migration to resolve conflict between 0015_add_affiliate_fields and 0016_otptoken

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_affiliate_fields'),
        ('accounts', '0016_otptoken'),
    ]

    operations = [
        # This is a merge migration that resolves the conflict
        # No operations needed as both migrations are independent
    ]

