# Generated by Django 4.2.0
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the video', max_length=255)),
                ('description', models.TextField(help_text='Description of the video content')),
                ('tag', models.CharField(help_text='Tag or category for the video', max_length=100)),
                ('video_hours', models.DecimalField(decimal_places=2, help_text='Duration of the video in hours', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', help_text='Current viewing status of the video', max_length=15)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of video watched (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('last_watched_at', models.DateTimeField(blank=True, help_text='Last time the video was watched', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='academy.video')),
            ],
            options={
                'verbose_name': 'User Video Progress',
                'verbose_name_plural': 'User Video Progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='uservideoprogress',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='academy_uservideoprogress_user_video_unique'),
        ),
    ]