# Generated by Django 5.2.1 on 2025-08-01 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uservideoprogress',
            name='academy_uservideoprogress_user_video_unique',
        ),
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together={('user', 'video')},
        ),
    ]
