# Generated by Django 4.2.0
import academy.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload the video file (supported formats: MP4, AVI, MOV, WMV, FLV, WebM, MKV)', null=True, upload_to=academy.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
    ]