# Generated by Django 5.2.1 on 2025-08-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_uservideoprogress_academy_uservideoprogress_user_video_unique_and_more'),
        ('academy', '0002_video_video_file'),
    ]

    operations = [
    ]
