# Generated by Django 5.1.5 on 2025-08-02 19:30

import academy.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_merge_20250801_0925'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='language',
            field=models.CharField(choices=[('persian', 'Persian (فارسی)'), ('arabic', 'Arabic (العربية)'), ('english', 'English'), ('turkish', 'Turkish (Türkçe)')], default='persian', help_text='Language for which progress is tracked', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='description_arabic',
            field=models.TextField(blank=True, help_text='Arabic description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_english',
            field=models.TextField(blank=True, help_text='English description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_persian',
            field=models.TextField(blank=True, help_text='Persian description'),
        ),
        migrations.AddField(
            model_name='video',
            name='description_turkish',
            field=models.TextField(blank=True, help_text='Turkish description'),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('persian', 'Persian (فارسی)'), ('arabic', 'Arabic (العربية)'), ('english', 'English'), ('turkish', 'Turkish (Türkçe)')], default='persian', help_text='Language of the video content', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='title_arabic',
            field=models.CharField(blank=True, help_text='Arabic title', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='title_english',
            field=models.CharField(blank=True, help_text='English title', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='title_persian',
            field=models.CharField(blank=True, help_text='Persian title', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='title_turkish',
            field=models.CharField(blank=True, help_text='Turkish title', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_arabic',
            field=models.FileField(blank=True, help_text='Arabic video file', null=True, upload_to=academy.models.video_upload_path_arabic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_english',
            field=models.FileField(blank=True, help_text='English video file', null=True, upload_to=academy.models.video_upload_path_english, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_persian',
            field=models.FileField(blank=True, help_text='Persian video file', null=True, upload_to=academy.models.video_upload_path_persian, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_turkish',
            field=models.FileField(blank=True, help_text='Turkish video file', null=True, upload_to=academy.models.video_upload_path_turkish, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Default video file (supported formats: MP4, AVI, MOV, WMV, FLV, WebM, MKV)', null=True, upload_to=academy.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mkv'])]),
        ),
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together={('user', 'video', 'language')},
        ),
    ]
