# Generated by Django 5.1.5 on 2025-11-27 09:01

import academy.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_uservideoprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='language',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_hours',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Default thumbnail image (supported formats: JPG, PNG, WEBP)', null=True, upload_to=academy.models.thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_arabic',
            field=models.ImageField(blank=True, help_text='Arabic thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_arabic),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_english',
            field=models.ImageField(blank=True, help_text='English thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_english),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_persian',
            field=models.ImageField(blank=True, help_text='Persian thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_persian),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_turkish',
            field=models.ImageField(blank=True, help_text='Turkish thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_turkish),
        ),
        migrations.AddField(
            model_name='video',
            name='video_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the video in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds (0-59)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
