# Generated by Django 5.1.5 on 2025-08-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_uservideoprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='language',
        ),
    ]
