# Generated by Django 5.1.5 on 2025-08-06 10:10

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_remove_video_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Default thumbnail image (supported formats: JPG, PNG, WEBP)', null=True, upload_to=academy.models.thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_arabic',
            field=models.ImageField(blank=True, help_text='Arabic thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_arabic),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_english',
            field=models.ImageField(blank=True, help_text='English thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_english),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_persian',
            field=models.ImageField(blank=True, help_text='Persian thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_persian),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_turkish',
            field=models.ImageField(blank=True, help_text='Turkish thumbnail image', null=True, upload_to=academy.models.thumbnail_upload_path_turkish),
        ),
    ]
