# Generated by Django 5.1.5 on 2025-08-15 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_add_thumbnail_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_hours',
        ),
        migrations.AddField(
            model_name='video',
            name='video_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the video in minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='video',
            name='video_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the video in seconds (0-59)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
