# Generated by Django 5.1.5 on 2025-08-19 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('when', 'When'), ('condition', 'Condition'), ('action', 'Action'), ('waiting', 'Waiting')], max_length=20)),
                ('title', models.CharField(help_text='Node title', max_length=200)),
                ('position_x', models.FloatField(default=0, help_text='X position in visual editor')),
                ('position_y', models.FloatField(default=0, help_text='Y position in visual editor')),
                ('configuration', models.JSONField(default=dict, help_text='Node-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['workflow', 'node_type', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='AI prompt for AI-based condition evaluation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('transfer_to_human', 'Transfer to Human'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status')], max_length=30),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('transfer_to_human', 'Transfer to Human'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], help_text='For scheduled triggers only', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='trigger_type',
            field=models.CharField(choices=[('MESSAGE_RECEIVED', 'Receive Message'), ('MESSAGE_SENT', 'Message Sent'), ('CONVERSATION_CREATED', 'Conversation Created'), ('CONVERSATION_CLOSED', 'Conversation Closed'), ('USER_CREATED', 'New Customer'), ('USER_UPDATED', 'User Updated'), ('TAG_ADDED', 'Add Tag'), ('TAG_REMOVED', 'Tag Removed'), ('FORM_SUBMITTED', 'Form Submitted'), ('SCHEDULED', 'Scheduled'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual'), ('CUSTOM', 'Custom')], max_length=30),
        ),
        migrations.CreateModel(
            name='ActionNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('transfer_to_human', 'Transfer to Human'), ('send_email', 'Send Email'), ('webhook', 'Webhook'), ('custom_code', 'Custom Code')], max_length=30)),
                ('message_content', models.TextField(blank=True, help_text='Message content for send_message action')),
                ('delay_amount', models.PositiveIntegerField(default=0, help_text='Delay amount')),
                ('delay_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', max_length=10)),
                ('redirect_destination', models.CharField(blank=True, choices=[('support', 'Support'), ('sales', 'Sales'), ('technical', 'Technical'), ('billing', 'Billing'), ('general', 'General')], help_text='Destination for conversation redirect', max_length=20)),
                ('tag_name', models.CharField(blank=True, help_text='Tag name for add/remove tag actions', max_length=100)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL')),
                ('webhook_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('webhook_headers', models.JSONField(default=dict, help_text='Webhook headers')),
                ('webhook_payload', models.JSONField(default=dict, help_text='Webhook payload')),
                ('custom_code', models.TextField(blank=True, help_text='Custom code to execute')),
            ],
            options={
                'verbose_name': 'Action Node',
                'verbose_name_plural': 'Action Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='ConditionNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=5)),
                ('conditions', models.JSONField(default=list, help_text='List of conditions to evaluate')),
            ],
            options={
                'verbose_name': 'Condition Node',
                'verbose_name_plural': 'Condition Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='WaitingNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('choice', 'Choice Answer')], max_length=20)),
                ('storage_type', models.CharField(choices=[('temporary', 'Temporary Storage'), ('customer_data', 'Customer Data')], default='temporary', max_length=20)),
                ('storage_field', models.CharField(blank=True, help_text='Field name to store answer', max_length=100)),
                ('customer_message', models.TextField(help_text='Message sent to customer requesting response')),
                ('choice_options', models.JSONField(default=list, help_text='Options for choice answer type')),
                ('allowed_errors', models.PositiveIntegerField(default=3, help_text='Number of allowed user errors')),
                ('skip_keywords', models.JSONField(default=list, help_text='Keywords that skip this step')),
                ('response_timeout', models.PositiveIntegerField(default=3600, help_text='Response timeout in seconds')),
            ],
            options={
                'verbose_name': 'Waiting Node',
                'verbose_name_plural': 'Waiting Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='WhenNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('when_type', models.CharField(choices=[('receive_message', 'Receive Message'), ('add_tag', 'Add Tag'), ('new_customer', 'New Customer'), ('scheduled', 'Scheduled')], max_length=30)),
                ('keywords', models.JSONField(default=list, help_text='Keywords for message triggers')),
                ('tags', models.JSONField(default=list, help_text='Tags for tag triggers')),
                ('channels', models.JSONField(default=list, help_text='Channels to monitor (instagram, telegram, all)')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'When Node',
                'verbose_name_plural': 'When Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('skip', 'Skip')], default='success', max_length=20)),
                ('condition', models.JSONField(default=dict, help_text='Optional condition for this connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflow.workflownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflow.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Node Connection',
                'verbose_name_plural': 'Node Connections',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='Customer ID', max_length=100)),
                ('conversation_id', models.CharField(help_text='Conversation ID', max_length=100)),
                ('response_value', models.TextField(help_text="User's response")),
                ('is_valid', models.BooleanField(default=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='workflow.workflowexecution')),
                ('waiting_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workflow.waitingnode')),
            ],
            options={
                'verbose_name': 'User Response',
                'verbose_name_plural': 'User Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'node_type'], name='workflow_wo_workflo_126083_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'is_active'], name='workflow_wo_workflo_6691f2_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeconnection',
            index=models.Index(fields=['workflow', 'source_node'], name='workflow_no_workflo_d89080_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeconnection',
            index=models.Index(fields=['workflow', 'target_node'], name='workflow_no_workflo_b683cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeconnection',
            unique_together={('source_node', 'target_node', 'connection_type')},
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['user_id', 'created_at'], name='workflow_us_user_id_276973_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['conversation_id', 'created_at'], name='workflow_us_convers_998d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['waiting_node', 'workflow_execution'], name='workflow_us_waiting_066df3_idx'),
        ),
    ]
