# Generated by Django 5.1.5 on 2025-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_fix_condition_node_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingnode',
            name='response_time_limit_enabled',
            field=models.BooleanField(default=True, help_text='Enable response time limit'),
        ),
        migrations.AddField(
            model_name='waitingnode',
            name='response_timeout_amount',
            field=models.PositiveIntegerField(default=30, help_text='Response timeout amount'),
        ),
        migrations.AddField(
            model_name='waitingnode',
            name='response_timeout_unit',
            field=models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', help_text='Response timeout unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='waitingnode',
            name='response_timeout',
            field=models.PositiveIntegerField(default=3600, help_text='Response timeout in seconds (legacy field)'),
        ),
        migrations.AlterField(
            model_name='waitingnode',
            name='storage_type',
            field=models.CharField(choices=[('user_profile', 'User Profile'), ('custom_field', 'Custom Field'), ('database', 'Database'), ('session', 'Session Storage'), ('temporary', 'Temporary Storage')], default='temporary', max_length=20),
        ),
    ]
