# Generated by Django 5.1.5 on 2025-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_remove_waitingnode_skip_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingnode',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Custom error message to send when validation fails. If empty, default error messages will be used.'),
        ),
    ]
