# Generated by Django 5.1.5 on 2025-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_actionnode_redirect_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whennode',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text='Channels to monitor (instagram, telegram, all)'),
        ),
        migrations.AlterField(
            model_name='whennode',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords for message triggers'),
        ),
        migrations.AlterField(
            model_name='whennode',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for tag triggers - filters customers by these tags'),
        ),
    ]
