# Generated by Django 5.1.5 on 2025-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alter_whennode_channels_alter_whennode_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whennode',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for tag triggers - workflow executes only if customer has ALL of these tags'),
        ),
    ]
