# Generated by Django 5.1.5 on 2025-08-13 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('wait', 'Wait'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status')], max_length=30)),
                ('configuration', models.JSONField(default=dict, help_text='Action-specific configuration (templates, settings, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution within workflow')),
                ('delay', models.PositiveIntegerField(default=0, help_text='Delay in seconds before executing this action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('wait', 'Wait'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status')], max_length=30)),
                ('configuration', models.JSONField(default=dict, help_text='Template configuration with placeholders')),
                ('use_custom_code', models.BooleanField(default=False)),
                ('custom_code', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action Template',
                'verbose_name_plural': 'Action Templates',
                'ordering': ['-is_featured', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=5)),
                ('conditions', models.JSONField(default=list, help_text='Array of condition rules in JSON format')),
                ('use_custom_code', models.BooleanField(default=False)),
                ('custom_code', models.TextField(blank=True, help_text='Custom Python code for complex conditions (executed in sandbox)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('code', models.CharField(help_text='Unique code for this event type', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('user', 'User'), ('conversation', 'Conversation'), ('message', 'Message'), ('system', 'System'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of when this event is triggered')),
                ('available_fields', models.JSONField(default=dict, help_text='JSON schema of fields available in event data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('MESSAGE_RECEIVED', 'Message Received'), ('MESSAGE_SENT', 'Message Sent'), ('CONVERSATION_CREATED', 'Conversation Created'), ('CONVERSATION_CLOSED', 'Conversation Closed'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('TAG_ADDED', 'Tag Added'), ('TAG_REMOVED', 'Tag Removed'), ('FORM_SUBMITTED', 'Form Submitted'), ('SCHEDULED', 'Scheduled'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual'), ('CUSTOM', 'Custom')], max_length=30)),
                ('configuration', models.JSONField(default=dict, help_text='Trigger-specific configuration (e.g., schedule details, webhook settings)')),
                ('filters', models.JSONField(default=dict, help_text='Conditions that must be met for this trigger to fire')),
                ('schedule_type', models.CharField(blank=True, choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], help_text='For scheduled triggers only', max_length=20, null=True)),
                ('next_execution', models.DateTimeField(blank=True, help_text='When this trigger should next execute (for scheduled triggers)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggerEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trigger Event Log',
                'verbose_name_plural': 'Trigger Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='workflow_tr_event_t_d516c3_idx'), models.Index(fields=['user_id', 'created_at'], name='workflow_tr_user_id_58018a_idx'), models.Index(fields=['conversation_id', 'created_at'], name='workflow_tr_convers_1aef85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('ui_settings', models.JSONField(default=dict, help_text='UI layout and visual settings for workflow editor')),
                ('edges', models.JSONField(default=list, help_text='Visual connections between workflow elements')),
                ('max_executions', models.PositiveIntegerField(default=0, help_text='Maximum executions per user (0 = unlimited)')),
                ('delay_between_executions', models.PositiveIntegerField(default=0, help_text='Minimum seconds between executions for same user')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Execution order within workflow')),
                ('is_required', models.BooleanField(default=True, help_text='Whether workflow should fail if this action fails')),
                ('add_result_to_context', models.BooleanField(default=False, help_text='Whether to add action result to workflow context for later actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_associations', to='workflow.action')),
                ('condition', models.ForeignKey(blank=True, help_text='Optional condition that must be true for this action to execute', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.condition')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'verbose_name_plural': 'Workflow Actions',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'action')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TIMED_OUT', 'Timed Out'), ('WAITING', 'Waiting')], default='PENDING', max_length=20)),
                ('user', models.CharField(blank=True, help_text='User ID (Customer ID) this execution is for', max_length=100, null=True)),
                ('conversation', models.CharField(blank=True, help_text='Conversation ID this execution is related to', max_length=100, null=True)),
                ('trigger_data', models.JSONField(default=dict, help_text='Original trigger data that started this execution')),
                ('context_data', models.JSONField(default=dict, help_text='Runtime context data available to actions')),
                ('result_data', models.JSONField(default=dict, help_text='Final execution results')),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Execution',
                'verbose_name_plural': 'Workflow Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('WAITING', 'Waiting')], default='PENDING', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflow.workflowaction')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='workflow.workflowexecution')),
            ],
            options={
                'verbose_name': 'Workflow Action Execution',
                'verbose_name_plural': 'Workflow Action Executions',
                'ordering': ['workflow_execution', 'workflow_action__order'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(help_text='Execution duration in seconds')),
                ('context', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.action')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['action', 'executed_at'], name='workflow_ac_action__0021de_idx'), models.Index(fields=['success', 'executed_at'], name='workflow_ac_success_b364f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TriggerWorkflowAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specific_conditions', models.JSONField(default=dict, help_text='Additional conditions specific to this trigger-workflow association')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Execution priority (lower numbers execute first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_associations', to='workflow.trigger')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_associations', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Trigger-Workflow Association',
                'verbose_name_plural': 'Trigger-Workflow Associations',
                'ordering': ['priority', '-created_at'],
                'unique_together': {('trigger', 'workflow')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'status'], name='workflow_wo_workflo_2daa18_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['user', 'created_at'], name='workflow_wo_user_d6d0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['conversation', 'created_at'], name='workflow_wo_convers_a44d06_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowactionexecution',
            index=models.Index(fields=['workflow_execution', 'status'], name='workflow_wo_workflo_0ada06_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowactionexecution',
            index=models.Index(fields=['status', 'next_retry_at'], name='workflow_wo_status_88c632_idx'),
        ),
    ]
