# Generated by Django 5.1.5 on 2025-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_add_node_based_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionnode',
            name='operator',
        ),
        migrations.AddField(
            model_name='conditionnode',
            name='combination_operator',
            field=models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='or', help_text='How to combine multiple conditions (AND/OR)', max_length=5),
        ),
        migrations.AlterField(
            model_name='conditionnode',
            name='conditions',
            field=models.JSONField(default=list, help_text='List of conditions - each with type, and specific fields based on type'),
        ),
    ]
