# Generated by Django 5.1.5 on 2025-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_update_waiting_node_storage_and_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionnode',
            name='ai_context_data',
            field=models.JSONField(default=dict, help_text='Additional context data for AI'),
        ),
        migrations.AddField(
            model_name='actionnode',
            name='ai_control_action',
            field=models.CharField(blank=True, choices=[('disable', 'Disable AI'), ('enable', 'Enable AI'), ('custom_prompt', 'Set Custom Prompt'), ('reset_context', 'Reset AI Context')], help_text='AI control action type', max_length=20),
        ),
        migrations.AddField(
            model_name='actionnode',
            name='ai_custom_prompt',
            field=models.TextField(blank=True, help_text='Custom AI prompt for this conversation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('transfer_to_human', 'Transfer to Human'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status'), ('control_ai_response', 'Control AI Response'), ('update_ai_context', 'Update AI Context')], max_length=30),
        ),
        migrations.AlterField(
            model_name='actionnode',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('transfer_to_human', 'Transfer to Human'), ('send_email', 'Send Email'), ('webhook', 'Webhook'), ('custom_code', 'Custom Code'), ('control_ai_response', 'Control AI Response'), ('update_ai_context', 'Update AI Context')], max_length=30),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('transfer_to_human', 'Transfer to Human'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status'), ('control_ai_response', 'Control AI Response'), ('update_ai_context', 'Update AI Context')], max_length=30),
        ),
    ]
