# Generated by Django 5.1.5 on 2025-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_add_ai_control_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingnode',
            name='answer_type',
        ),
        migrations.AlterField(
            model_name='waitingnode',
            name='storage_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20),
        ),
    ]
