# Generated by Django 5.1.5 on 2025-09-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_waitingnode_answer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingnode',
            name='storage_field',
        ),
    ]
