# Generated by Django 5.1.5 on 2025-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_remove_waitingnode_storage_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingnode',
            name='skip_keywords',
        ),
        migrations.AddField(
            model_name='waitingnode',
            name='exit_keywords',
            field=models.JSONField(default=list, help_text='Keywords that exit this step unsuccessfully'),
        ),
    ]
