# Generated by Django 5.1.5 on 2025-10-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_add_error_message_to_waiting_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionnode',
            name='redirect_destination',
            field=models.CharField(blank=True, choices=[('ai', 'AI Assistant'), ('support', 'Support'), ('sales', 'Sales'), ('technical', 'Technical'), ('billing', 'Billing'), ('general', 'General')], help_text='Destination for conversation redirect', max_length=20),
        ),
    ]
