# Generated by Django 5.1.5 on 2025-11-25 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alter_whennode_channels_alter_whennode_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('when', 'When'), ('condition', 'Condition'), ('action', 'Action'), ('waiting', 'Waiting')], max_length=20)),
                ('title', models.CharField(help_text='Node title', max_length=200)),
                ('position_x', models.FloatField(default=0, help_text='X position in visual editor')),
                ('position_y', models.FloatField(default=0, help_text='Y position in visual editor')),
                ('configuration', models.JSONField(default=dict, help_text='Node-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['workflow', 'node_type', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='ai_prompt',
            field=models.TextField(blank=True, help_text='AI prompt for AI-based condition evaluation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('transfer_to_human', 'Transfer to Human'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status'), ('control_ai_response', 'Control AI Response'), ('update_ai_context', 'Update AI Context'), ('instagram_comment_dm_reply', 'Instagram Comment → DM + Reply')], max_length=30),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='action_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('update_user', 'Update User'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('send_email', 'Send Email'), ('add_note', 'Add Note'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('transfer_to_human', 'Transfer to Human'), ('custom_code', 'Custom Code'), ('set_conversation_status', 'Set Conversation Status'), ('control_ai_response', 'Control AI Response'), ('update_ai_context', 'Update AI Context'), ('instagram_comment_dm_reply', 'Instagram Comment → DM + Reply')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], help_text='For scheduled triggers only', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='trigger_type',
            field=models.CharField(choices=[('MESSAGE_RECEIVED', 'Receive Message'), ('MESSAGE_SENT', 'Message Sent'), ('CONVERSATION_CREATED', 'Conversation Created'), ('CONVERSATION_CLOSED', 'Conversation Closed'), ('USER_CREATED', 'New Customer'), ('USER_UPDATED', 'User Updated'), ('TAG_ADDED', 'Add Tag'), ('TAG_REMOVED', 'Tag Removed'), ('FORM_SUBMITTED', 'Form Submitted'), ('SCHEDULED', 'Scheduled'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual'), ('CUSTOM', 'Custom'), ('INSTAGRAM_COMMENT', 'Instagram Comment')], max_length=30),
        ),
        migrations.CreateModel(
            name='ActionNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('delay', 'Delay'), ('redirect_conversation', 'Redirect Conversation'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('transfer_to_human', 'Transfer to Human'), ('send_email', 'Send Email'), ('webhook', 'Webhook'), ('custom_code', 'Custom Code'), ('control_ai_response', 'Control AI Response'), ('update_ai_context', 'Update AI Context'), ('instagram_comment_dm_reply', 'Instagram Comment → DM + Reply')], max_length=30)),
                ('message_content', models.TextField(blank=True, help_text='Message content for send_message action')),
                ('delay_amount', models.PositiveIntegerField(default=0, help_text='Delay amount')),
                ('delay_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', max_length=10)),
                ('redirect_destination', models.CharField(blank=True, choices=[('ai', 'AI Assistant'), ('support', 'Support'), ('sales', 'Sales'), ('technical', 'Technical'), ('billing', 'Billing'), ('general', 'General')], help_text='Destination for conversation redirect', max_length=20)),
                ('tag_name', models.CharField(blank=True, help_text='Tag name for add/remove tag actions', max_length=100)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL')),
                ('webhook_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('webhook_headers', models.JSONField(default=dict, help_text='Webhook headers')),
                ('webhook_payload', models.JSONField(default=dict, help_text='Webhook payload')),
                ('custom_code', models.TextField(blank=True, help_text='Custom code to execute')),
                ('ai_control_action', models.CharField(blank=True, choices=[('disable', 'Disable AI'), ('enable', 'Enable AI'), ('custom_prompt', 'Set Custom Prompt'), ('reset_context', 'Reset AI Context')], help_text='AI control action type', max_length=20)),
                ('ai_custom_prompt', models.TextField(blank=True, help_text='Custom AI prompt for this conversation')),
                ('ai_context_data', models.JSONField(default=dict, help_text='Additional context data for AI')),
                ('instagram_dm_mode', models.CharField(blank=True, choices=[('STATIC', 'Static Message'), ('PRODUCT', 'Product-based AI Message')], default='STATIC', help_text='DM mode: static template or AI-generated product message', max_length=20)),
                ('instagram_dm_text_template', models.TextField(blank=True, help_text='Template for static DM (supports {{username}}, {{comment_text}}, etc.)')),
                ('instagram_product_id', models.UUIDField(blank=True, help_text='Product ID for PRODUCT mode (AI will generate DM based on this product)', null=True)),
                ('instagram_public_reply_enabled', models.BooleanField(default=False, help_text='Whether to send a public reply to the comment')),
                ('instagram_public_reply_text', models.TextField(blank=True, help_text='Template for public reply (supports {{username}}, etc.)')),
            ],
            options={
                'verbose_name': 'Action Node',
                'verbose_name_plural': 'Action Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='ConditionNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('combination_operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='or', help_text='How to combine multiple conditions (AND/OR)', max_length=5)),
                ('conditions', models.JSONField(default=list, help_text='List of conditions - each with type, and specific fields based on type')),
            ],
            options={
                'verbose_name': 'Condition Node',
                'verbose_name_plural': 'Condition Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='WaitingNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('storage_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone')], default='text', max_length=20)),
                ('customer_message', models.TextField(help_text='Message sent to customer requesting response')),
                ('error_message', models.TextField(blank=True, default='', help_text='Custom error message to send when validation fails. If empty, default error messages will be used.')),
                ('choice_options', models.JSONField(default=list, help_text='Options for choice answer type')),
                ('allowed_errors', models.PositiveIntegerField(default=3, help_text='Number of allowed user errors')),
                ('exit_keywords', models.JSONField(default=list, help_text='Keywords that exit this step unsuccessfully')),
                ('response_time_limit_enabled', models.BooleanField(default=True, help_text='Enable response time limit')),
                ('response_timeout_amount', models.PositiveIntegerField(default=30, help_text='Response timeout amount')),
                ('response_timeout_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', help_text='Response timeout unit', max_length=10)),
                ('response_timeout', models.PositiveIntegerField(default=3600, help_text='Response timeout in seconds (legacy field)')),
            ],
            options={
                'verbose_name': 'Waiting Node',
                'verbose_name_plural': 'Waiting Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='WhenNode',
            fields=[
                ('workflownode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workflow.workflownode')),
                ('when_type', models.CharField(choices=[('receive_message', 'Receive Message'), ('add_tag', 'Add Tag'), ('new_customer', 'New Customer'), ('scheduled', 'Scheduled'), ('instagram_comment', 'Instagram Comment')], max_length=30)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords for message triggers')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for tag triggers - workflow executes only if customer has ALL of these tags')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Channels to monitor (instagram, telegram, all)')),
                ('instagram_post_url', models.URLField(blank=True, help_text='Filter: Only trigger for comments on this specific post (optional). Leave empty for all posts.', null=True)),
                ('instagram_media_type', models.CharField(blank=True, choices=[('all', 'All'), ('post', 'Post Only'), ('reel', 'Reel Only'), ('video', 'Video Only')], default='all', help_text='Filter: Type of Instagram media to monitor', max_length=20)),
                ('comment_keywords', models.JSONField(blank=True, default=list, help_text='Filter: Only trigger if comment contains these keywords (case-insensitive)')),
                ('schedule_frequency', models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'When Node',
                'verbose_name_plural': 'When Nodes',
            },
            bases=('workflow.workflownode',),
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('skip', 'Skip')], default='success', max_length=20)),
                ('condition', models.JSONField(default=dict, help_text='Optional condition for this connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflow.workflownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflow.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Node Connection',
                'verbose_name_plural': 'Node Connections',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='Customer ID', max_length=100)),
                ('conversation_id', models.CharField(help_text='Conversation ID', max_length=100)),
                ('response_value', models.TextField(help_text="User's response")),
                ('is_valid', models.BooleanField(default=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='workflow.workflowexecution')),
                ('waiting_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workflow.waitingnode')),
            ],
            options={
                'verbose_name': 'User Response',
                'verbose_name_plural': 'User Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'node_type'], name='workflow_wo_workflo_126083_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'is_active'], name='workflow_wo_workflo_6691f2_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeconnection',
            index=models.Index(fields=['workflow', 'source_node'], name='workflow_no_workflo_d89080_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeconnection',
            index=models.Index(fields=['workflow', 'target_node'], name='workflow_no_workflo_b683cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeconnection',
            unique_together={('source_node', 'target_node', 'connection_type')},
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['user_id', 'created_at'], name='workflow_us_user_id_276973_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['conversation_id', 'created_at'], name='workflow_us_convers_998d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['waiting_node', 'workflow_execution'], name='workflow_us_waiting_066df3_idx'),
        ),
    ]
